// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/bbrownsound/flink/formats/proto/test/v1/test_map.proto

package com.bbrownsound.flink.formats.proto.test.v1;

public final class TestMap {
  private TestMap() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface NestedMapOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.bbrownsound.flink.formats.proto.test.v1.NestedMap)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string id = 1 [json_name = "id"];</code>
     * @return The id.
     */
    java.lang.String getId();
    /**
     * <code>string id = 1 [json_name = "id"];</code>
     * @return The bytes for id.
     */
    com.google.protobuf.ByteString
        getIdBytes();
  }
  /**
   * Protobuf type {@code com.bbrownsound.flink.formats.proto.test.v1.NestedMap}
   */
  public static final class NestedMap extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.bbrownsound.flink.formats.proto.test.v1.NestedMap)
      NestedMapOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use NestedMap.newBuilder() to construct.
    private NestedMap(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private NestedMap() {
      id_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new NestedMap();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bbrownsound.flink.formats.proto.test.v1.TestMap.internal_static_com_bbrownsound_flink_formats_proto_test_v1_NestedMap_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bbrownsound.flink.formats.proto.test.v1.TestMap.internal_static_com_bbrownsound_flink_formats_proto_test_v1_NestedMap_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.bbrownsound.flink.formats.proto.test.v1.TestMap.NestedMap.class, com.bbrownsound.flink.formats.proto.test.v1.TestMap.NestedMap.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object id_ = "";
    /**
     * <code>string id = 1 [json_name = "id"];</code>
     * @return The id.
     */
    @java.lang.Override
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /**
     * <code>string id = 1 [json_name = "id"];</code>
     * @return The bytes for id.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(id_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(id_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.bbrownsound.flink.formats.proto.test.v1.TestMap.NestedMap)) {
        return super.equals(obj);
      }
      com.bbrownsound.flink.formats.proto.test.v1.TestMap.NestedMap other = (com.bbrownsound.flink.formats.proto.test.v1.TestMap.NestedMap) obj;

      if (!getId()
          .equals(other.getId())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.bbrownsound.flink.formats.proto.test.v1.TestMap.NestedMap parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bbrownsound.flink.formats.proto.test.v1.TestMap.NestedMap parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bbrownsound.flink.formats.proto.test.v1.TestMap.NestedMap parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bbrownsound.flink.formats.proto.test.v1.TestMap.NestedMap parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bbrownsound.flink.formats.proto.test.v1.TestMap.NestedMap parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bbrownsound.flink.formats.proto.test.v1.TestMap.NestedMap parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bbrownsound.flink.formats.proto.test.v1.TestMap.NestedMap parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.bbrownsound.flink.formats.proto.test.v1.TestMap.NestedMap parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.bbrownsound.flink.formats.proto.test.v1.TestMap.NestedMap parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.bbrownsound.flink.formats.proto.test.v1.TestMap.NestedMap parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.bbrownsound.flink.formats.proto.test.v1.TestMap.NestedMap parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.bbrownsound.flink.formats.proto.test.v1.TestMap.NestedMap parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.bbrownsound.flink.formats.proto.test.v1.TestMap.NestedMap prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.bbrownsound.flink.formats.proto.test.v1.NestedMap}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.bbrownsound.flink.formats.proto.test.v1.NestedMap)
        com.bbrownsound.flink.formats.proto.test.v1.TestMap.NestedMapOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.bbrownsound.flink.formats.proto.test.v1.TestMap.internal_static_com_bbrownsound_flink_formats_proto_test_v1_NestedMap_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.bbrownsound.flink.formats.proto.test.v1.TestMap.internal_static_com_bbrownsound_flink_formats_proto_test_v1_NestedMap_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.bbrownsound.flink.formats.proto.test.v1.TestMap.NestedMap.class, com.bbrownsound.flink.formats.proto.test.v1.TestMap.NestedMap.Builder.class);
      }

      // Construct using com.bbrownsound.flink.formats.proto.test.v1.TestMap.NestedMap.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        id_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.bbrownsound.flink.formats.proto.test.v1.TestMap.internal_static_com_bbrownsound_flink_formats_proto_test_v1_NestedMap_descriptor;
      }

      @java.lang.Override
      public com.bbrownsound.flink.formats.proto.test.v1.TestMap.NestedMap getDefaultInstanceForType() {
        return com.bbrownsound.flink.formats.proto.test.v1.TestMap.NestedMap.getDefaultInstance();
      }

      @java.lang.Override
      public com.bbrownsound.flink.formats.proto.test.v1.TestMap.NestedMap build() {
        com.bbrownsound.flink.formats.proto.test.v1.TestMap.NestedMap result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.bbrownsound.flink.formats.proto.test.v1.TestMap.NestedMap buildPartial() {
        com.bbrownsound.flink.formats.proto.test.v1.TestMap.NestedMap result = new com.bbrownsound.flink.formats.proto.test.v1.TestMap.NestedMap(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.bbrownsound.flink.formats.proto.test.v1.TestMap.NestedMap result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.id_ = id_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.bbrownsound.flink.formats.proto.test.v1.TestMap.NestedMap) {
          return mergeFrom((com.bbrownsound.flink.formats.proto.test.v1.TestMap.NestedMap)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.bbrownsound.flink.formats.proto.test.v1.TestMap.NestedMap other) {
        if (other == com.bbrownsound.flink.formats.proto.test.v1.TestMap.NestedMap.getDefaultInstance()) return this;
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                id_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object id_ = "";
      /**
       * <code>string id = 1 [json_name = "id"];</code>
       * @return The id.
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string id = 1 [json_name = "id"];</code>
       * @return The bytes for id.
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string id = 1 [json_name = "id"];</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        id_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1 [json_name = "id"];</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        id_ = getDefaultInstance().getId();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1 [json_name = "id"];</code>
       * @param value The bytes for id to set.
       * @return This builder for chaining.
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        id_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.bbrownsound.flink.formats.proto.test.v1.NestedMap)
    }

    // @@protoc_insertion_point(class_scope:com.bbrownsound.flink.formats.proto.test.v1.NestedMap)
    private static final com.bbrownsound.flink.formats.proto.test.v1.TestMap.NestedMap DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.bbrownsound.flink.formats.proto.test.v1.TestMap.NestedMap();
    }

    public static com.bbrownsound.flink.formats.proto.test.v1.TestMap.NestedMap getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<NestedMap>
        PARSER = new com.google.protobuf.AbstractParser<NestedMap>() {
      @java.lang.Override
      public NestedMap parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<NestedMap> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<NestedMap> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.bbrownsound.flink.formats.proto.test.v1.TestMap.NestedMap getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MapTestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.bbrownsound.flink.formats.proto.test.v1.MapTest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>map&lt;string, string&gt; simple_string_map = 1 [json_name = "simpleStringMap"];</code>
     */
    int getSimpleStringMapCount();
    /**
     * <code>map&lt;string, string&gt; simple_string_map = 1 [json_name = "simpleStringMap"];</code>
     */
    boolean containsSimpleStringMap(
        java.lang.String key);
    /**
     * Use {@link #getSimpleStringMapMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, java.lang.String>
    getSimpleStringMap();
    /**
     * <code>map&lt;string, string&gt; simple_string_map = 1 [json_name = "simpleStringMap"];</code>
     */
    java.util.Map<java.lang.String, java.lang.String>
    getSimpleStringMapMap();
    /**
     * <code>map&lt;string, string&gt; simple_string_map = 1 [json_name = "simpleStringMap"];</code>
     */
    /* nullable */
java.lang.String getSimpleStringMapOrDefault(
        java.lang.String key,
        /* nullable */
java.lang.String defaultValue);
    /**
     * <code>map&lt;string, string&gt; simple_string_map = 1 [json_name = "simpleStringMap"];</code>
     */
    java.lang.String getSimpleStringMapOrThrow(
        java.lang.String key);

    /**
     * <code>map&lt;string, .com.bbrownsound.flink.formats.proto.test.v1.NestedMap&gt; nested_map = 2 [json_name = "nestedMap"];</code>
     */
    int getNestedMapCount();
    /**
     * <code>map&lt;string, .com.bbrownsound.flink.formats.proto.test.v1.NestedMap&gt; nested_map = 2 [json_name = "nestedMap"];</code>
     */
    boolean containsNestedMap(
        java.lang.String key);
    /**
     * Use {@link #getNestedMapMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, com.bbrownsound.flink.formats.proto.test.v1.TestMap.NestedMap>
    getNestedMap();
    /**
     * <code>map&lt;string, .com.bbrownsound.flink.formats.proto.test.v1.NestedMap&gt; nested_map = 2 [json_name = "nestedMap"];</code>
     */
    java.util.Map<java.lang.String, com.bbrownsound.flink.formats.proto.test.v1.TestMap.NestedMap>
    getNestedMapMap();
    /**
     * <code>map&lt;string, .com.bbrownsound.flink.formats.proto.test.v1.NestedMap&gt; nested_map = 2 [json_name = "nestedMap"];</code>
     */
    /* nullable */
com.bbrownsound.flink.formats.proto.test.v1.TestMap.NestedMap getNestedMapOrDefault(
        java.lang.String key,
        /* nullable */
com.bbrownsound.flink.formats.proto.test.v1.TestMap.NestedMap defaultValue);
    /**
     * <code>map&lt;string, .com.bbrownsound.flink.formats.proto.test.v1.NestedMap&gt; nested_map = 2 [json_name = "nestedMap"];</code>
     */
    com.bbrownsound.flink.formats.proto.test.v1.TestMap.NestedMap getNestedMapOrThrow(
        java.lang.String key);
  }
  /**
   * Protobuf type {@code com.bbrownsound.flink.formats.proto.test.v1.MapTest}
   */
  public static final class MapTest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.bbrownsound.flink.formats.proto.test.v1.MapTest)
      MapTestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MapTest.newBuilder() to construct.
    private MapTest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MapTest() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new MapTest();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bbrownsound.flink.formats.proto.test.v1.TestMap.internal_static_com_bbrownsound_flink_formats_proto_test_v1_MapTest_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @java.lang.Override
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetSimpleStringMap();
        case 2:
          return internalGetNestedMap();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bbrownsound.flink.formats.proto.test.v1.TestMap.internal_static_com_bbrownsound_flink_formats_proto_test_v1_MapTest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.bbrownsound.flink.formats.proto.test.v1.TestMap.MapTest.class, com.bbrownsound.flink.formats.proto.test.v1.TestMap.MapTest.Builder.class);
    }

    public static final int SIMPLE_STRING_MAP_FIELD_NUMBER = 1;
    private static final class SimpleStringMapDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, java.lang.String> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, java.lang.String>newDefaultInstance(
                  com.bbrownsound.flink.formats.proto.test.v1.TestMap.internal_static_com_bbrownsound_flink_formats_proto_test_v1_MapTest_SimpleStringMapEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "");
    }
    @SuppressWarnings("serial")
    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> simpleStringMap_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetSimpleStringMap() {
      if (simpleStringMap_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            SimpleStringMapDefaultEntryHolder.defaultEntry);
      }
      return simpleStringMap_;
    }
    public int getSimpleStringMapCount() {
      return internalGetSimpleStringMap().getMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; simple_string_map = 1 [json_name = "simpleStringMap"];</code>
     */
    @java.lang.Override
    public boolean containsSimpleStringMap(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetSimpleStringMap().getMap().containsKey(key);
    }
    /**
     * Use {@link #getSimpleStringMapMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getSimpleStringMap() {
      return getSimpleStringMapMap();
    }
    /**
     * <code>map&lt;string, string&gt; simple_string_map = 1 [json_name = "simpleStringMap"];</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.String, java.lang.String> getSimpleStringMapMap() {
      return internalGetSimpleStringMap().getMap();
    }
    /**
     * <code>map&lt;string, string&gt; simple_string_map = 1 [json_name = "simpleStringMap"];</code>
     */
    @java.lang.Override
    public /* nullable */
java.lang.String getSimpleStringMapOrDefault(
        java.lang.String key,
        /* nullable */
java.lang.String defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetSimpleStringMap().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; simple_string_map = 1 [json_name = "simpleStringMap"];</code>
     */
    @java.lang.Override
    public java.lang.String getSimpleStringMapOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetSimpleStringMap().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    public static final int NESTED_MAP_FIELD_NUMBER = 2;
    private static final class NestedMapDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, com.bbrownsound.flink.formats.proto.test.v1.TestMap.NestedMap> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, com.bbrownsound.flink.formats.proto.test.v1.TestMap.NestedMap>newDefaultInstance(
                  com.bbrownsound.flink.formats.proto.test.v1.TestMap.internal_static_com_bbrownsound_flink_formats_proto_test_v1_MapTest_NestedMapEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.MESSAGE,
                  com.bbrownsound.flink.formats.proto.test.v1.TestMap.NestedMap.getDefaultInstance());
    }
    @SuppressWarnings("serial")
    private com.google.protobuf.MapField<
        java.lang.String, com.bbrownsound.flink.formats.proto.test.v1.TestMap.NestedMap> nestedMap_;
    private com.google.protobuf.MapField<java.lang.String, com.bbrownsound.flink.formats.proto.test.v1.TestMap.NestedMap>
    internalGetNestedMap() {
      if (nestedMap_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            NestedMapDefaultEntryHolder.defaultEntry);
      }
      return nestedMap_;
    }
    public int getNestedMapCount() {
      return internalGetNestedMap().getMap().size();
    }
    /**
     * <code>map&lt;string, .com.bbrownsound.flink.formats.proto.test.v1.NestedMap&gt; nested_map = 2 [json_name = "nestedMap"];</code>
     */
    @java.lang.Override
    public boolean containsNestedMap(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetNestedMap().getMap().containsKey(key);
    }
    /**
     * Use {@link #getNestedMapMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, com.bbrownsound.flink.formats.proto.test.v1.TestMap.NestedMap> getNestedMap() {
      return getNestedMapMap();
    }
    /**
     * <code>map&lt;string, .com.bbrownsound.flink.formats.proto.test.v1.NestedMap&gt; nested_map = 2 [json_name = "nestedMap"];</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.String, com.bbrownsound.flink.formats.proto.test.v1.TestMap.NestedMap> getNestedMapMap() {
      return internalGetNestedMap().getMap();
    }
    /**
     * <code>map&lt;string, .com.bbrownsound.flink.formats.proto.test.v1.NestedMap&gt; nested_map = 2 [json_name = "nestedMap"];</code>
     */
    @java.lang.Override
    public /* nullable */
com.bbrownsound.flink.formats.proto.test.v1.TestMap.NestedMap getNestedMapOrDefault(
        java.lang.String key,
        /* nullable */
com.bbrownsound.flink.formats.proto.test.v1.TestMap.NestedMap defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, com.bbrownsound.flink.formats.proto.test.v1.TestMap.NestedMap> map =
          internalGetNestedMap().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, .com.bbrownsound.flink.formats.proto.test.v1.NestedMap&gt; nested_map = 2 [json_name = "nestedMap"];</code>
     */
    @java.lang.Override
    public com.bbrownsound.flink.formats.proto.test.v1.TestMap.NestedMap getNestedMapOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, com.bbrownsound.flink.formats.proto.test.v1.TestMap.NestedMap> map =
          internalGetNestedMap().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetSimpleStringMap(),
          SimpleStringMapDefaultEntryHolder.defaultEntry,
          1);
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetNestedMap(),
          NestedMapDefaultEntryHolder.defaultEntry,
          2);
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
           : internalGetSimpleStringMap().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
        simpleStringMap__ = SimpleStringMapDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(1, simpleStringMap__);
      }
      for (java.util.Map.Entry<java.lang.String, com.bbrownsound.flink.formats.proto.test.v1.TestMap.NestedMap> entry
           : internalGetNestedMap().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, com.bbrownsound.flink.formats.proto.test.v1.TestMap.NestedMap>
        nestedMap__ = NestedMapDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(2, nestedMap__);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.bbrownsound.flink.formats.proto.test.v1.TestMap.MapTest)) {
        return super.equals(obj);
      }
      com.bbrownsound.flink.formats.proto.test.v1.TestMap.MapTest other = (com.bbrownsound.flink.formats.proto.test.v1.TestMap.MapTest) obj;

      if (!internalGetSimpleStringMap().equals(
          other.internalGetSimpleStringMap())) return false;
      if (!internalGetNestedMap().equals(
          other.internalGetNestedMap())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (!internalGetSimpleStringMap().getMap().isEmpty()) {
        hash = (37 * hash) + SIMPLE_STRING_MAP_FIELD_NUMBER;
        hash = (53 * hash) + internalGetSimpleStringMap().hashCode();
      }
      if (!internalGetNestedMap().getMap().isEmpty()) {
        hash = (37 * hash) + NESTED_MAP_FIELD_NUMBER;
        hash = (53 * hash) + internalGetNestedMap().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.bbrownsound.flink.formats.proto.test.v1.TestMap.MapTest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bbrownsound.flink.formats.proto.test.v1.TestMap.MapTest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bbrownsound.flink.formats.proto.test.v1.TestMap.MapTest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bbrownsound.flink.formats.proto.test.v1.TestMap.MapTest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bbrownsound.flink.formats.proto.test.v1.TestMap.MapTest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bbrownsound.flink.formats.proto.test.v1.TestMap.MapTest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bbrownsound.flink.formats.proto.test.v1.TestMap.MapTest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.bbrownsound.flink.formats.proto.test.v1.TestMap.MapTest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.bbrownsound.flink.formats.proto.test.v1.TestMap.MapTest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.bbrownsound.flink.formats.proto.test.v1.TestMap.MapTest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.bbrownsound.flink.formats.proto.test.v1.TestMap.MapTest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.bbrownsound.flink.formats.proto.test.v1.TestMap.MapTest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.bbrownsound.flink.formats.proto.test.v1.TestMap.MapTest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.bbrownsound.flink.formats.proto.test.v1.MapTest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.bbrownsound.flink.formats.proto.test.v1.MapTest)
        com.bbrownsound.flink.formats.proto.test.v1.TestMap.MapTestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.bbrownsound.flink.formats.proto.test.v1.TestMap.internal_static_com_bbrownsound_flink_formats_proto_test_v1_MapTest_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 1:
            return internalGetSimpleStringMap();
          case 2:
            return internalGetNestedMap();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 1:
            return internalGetMutableSimpleStringMap();
          case 2:
            return internalGetMutableNestedMap();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.bbrownsound.flink.formats.proto.test.v1.TestMap.internal_static_com_bbrownsound_flink_formats_proto_test_v1_MapTest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.bbrownsound.flink.formats.proto.test.v1.TestMap.MapTest.class, com.bbrownsound.flink.formats.proto.test.v1.TestMap.MapTest.Builder.class);
      }

      // Construct using com.bbrownsound.flink.formats.proto.test.v1.TestMap.MapTest.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        internalGetMutableSimpleStringMap().clear();
        internalGetMutableNestedMap().clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.bbrownsound.flink.formats.proto.test.v1.TestMap.internal_static_com_bbrownsound_flink_formats_proto_test_v1_MapTest_descriptor;
      }

      @java.lang.Override
      public com.bbrownsound.flink.formats.proto.test.v1.TestMap.MapTest getDefaultInstanceForType() {
        return com.bbrownsound.flink.formats.proto.test.v1.TestMap.MapTest.getDefaultInstance();
      }

      @java.lang.Override
      public com.bbrownsound.flink.formats.proto.test.v1.TestMap.MapTest build() {
        com.bbrownsound.flink.formats.proto.test.v1.TestMap.MapTest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.bbrownsound.flink.formats.proto.test.v1.TestMap.MapTest buildPartial() {
        com.bbrownsound.flink.formats.proto.test.v1.TestMap.MapTest result = new com.bbrownsound.flink.formats.proto.test.v1.TestMap.MapTest(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.bbrownsound.flink.formats.proto.test.v1.TestMap.MapTest result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.simpleStringMap_ = internalGetSimpleStringMap();
          result.simpleStringMap_.makeImmutable();
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.nestedMap_ = internalGetNestedMap();
          result.nestedMap_.makeImmutable();
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.bbrownsound.flink.formats.proto.test.v1.TestMap.MapTest) {
          return mergeFrom((com.bbrownsound.flink.formats.proto.test.v1.TestMap.MapTest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.bbrownsound.flink.formats.proto.test.v1.TestMap.MapTest other) {
        if (other == com.bbrownsound.flink.formats.proto.test.v1.TestMap.MapTest.getDefaultInstance()) return this;
        internalGetMutableSimpleStringMap().mergeFrom(
            other.internalGetSimpleStringMap());
        bitField0_ |= 0x00000001;
        internalGetMutableNestedMap().mergeFrom(
            other.internalGetNestedMap());
        bitField0_ |= 0x00000002;
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
                simpleStringMap__ = input.readMessage(
                    SimpleStringMapDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
                internalGetMutableSimpleStringMap().getMutableMap().put(
                    simpleStringMap__.getKey(), simpleStringMap__.getValue());
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                com.google.protobuf.MapEntry<java.lang.String, com.bbrownsound.flink.formats.proto.test.v1.TestMap.NestedMap>
                nestedMap__ = input.readMessage(
                    NestedMapDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
                internalGetMutableNestedMap().getMutableMap().put(
                    nestedMap__.getKey(), nestedMap__.getValue());
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.MapField<
          java.lang.String, java.lang.String> simpleStringMap_;
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
          internalGetSimpleStringMap() {
        if (simpleStringMap_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              SimpleStringMapDefaultEntryHolder.defaultEntry);
        }
        return simpleStringMap_;
      }
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
          internalGetMutableSimpleStringMap() {
        if (simpleStringMap_ == null) {
          simpleStringMap_ = com.google.protobuf.MapField.newMapField(
              SimpleStringMapDefaultEntryHolder.defaultEntry);
        }
        if (!simpleStringMap_.isMutable()) {
          simpleStringMap_ = simpleStringMap_.copy();
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return simpleStringMap_;
      }
      public int getSimpleStringMapCount() {
        return internalGetSimpleStringMap().getMap().size();
      }
      /**
       * <code>map&lt;string, string&gt; simple_string_map = 1 [json_name = "simpleStringMap"];</code>
       */
      @java.lang.Override
      public boolean containsSimpleStringMap(
          java.lang.String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        return internalGetSimpleStringMap().getMap().containsKey(key);
      }
      /**
       * Use {@link #getSimpleStringMapMap()} instead.
       */
      @java.lang.Override
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String> getSimpleStringMap() {
        return getSimpleStringMapMap();
      }
      /**
       * <code>map&lt;string, string&gt; simple_string_map = 1 [json_name = "simpleStringMap"];</code>
       */
      @java.lang.Override
      public java.util.Map<java.lang.String, java.lang.String> getSimpleStringMapMap() {
        return internalGetSimpleStringMap().getMap();
      }
      /**
       * <code>map&lt;string, string&gt; simple_string_map = 1 [json_name = "simpleStringMap"];</code>
       */
      @java.lang.Override
      public /* nullable */
java.lang.String getSimpleStringMapOrDefault(
          java.lang.String key,
          /* nullable */
java.lang.String defaultValue) {
        if (key == null) { throw new NullPointerException("map key"); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetSimpleStringMap().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, string&gt; simple_string_map = 1 [json_name = "simpleStringMap"];</code>
       */
      @java.lang.Override
      public java.lang.String getSimpleStringMapOrThrow(
          java.lang.String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetSimpleStringMap().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }
      public Builder clearSimpleStringMap() {
        bitField0_ = (bitField0_ & ~0x00000001);
        internalGetMutableSimpleStringMap().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; simple_string_map = 1 [json_name = "simpleStringMap"];</code>
       */
      public Builder removeSimpleStringMap(
          java.lang.String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        internalGetMutableSimpleStringMap().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String>
          getMutableSimpleStringMap() {
        bitField0_ |= 0x00000001;
        return internalGetMutableSimpleStringMap().getMutableMap();
      }
      /**
       * <code>map&lt;string, string&gt; simple_string_map = 1 [json_name = "simpleStringMap"];</code>
       */
      public Builder putSimpleStringMap(
          java.lang.String key,
          java.lang.String value) {
        if (key == null) { throw new NullPointerException("map key"); }
        if (value == null) { throw new NullPointerException("map value"); }
        internalGetMutableSimpleStringMap().getMutableMap()
            .put(key, value);
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; simple_string_map = 1 [json_name = "simpleStringMap"];</code>
       */
      public Builder putAllSimpleStringMap(
          java.util.Map<java.lang.String, java.lang.String> values) {
        internalGetMutableSimpleStringMap().getMutableMap()
            .putAll(values);
        bitField0_ |= 0x00000001;
        return this;
      }

      private com.google.protobuf.MapField<
          java.lang.String, com.bbrownsound.flink.formats.proto.test.v1.TestMap.NestedMap> nestedMap_;
      private com.google.protobuf.MapField<java.lang.String, com.bbrownsound.flink.formats.proto.test.v1.TestMap.NestedMap>
          internalGetNestedMap() {
        if (nestedMap_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              NestedMapDefaultEntryHolder.defaultEntry);
        }
        return nestedMap_;
      }
      private com.google.protobuf.MapField<java.lang.String, com.bbrownsound.flink.formats.proto.test.v1.TestMap.NestedMap>
          internalGetMutableNestedMap() {
        if (nestedMap_ == null) {
          nestedMap_ = com.google.protobuf.MapField.newMapField(
              NestedMapDefaultEntryHolder.defaultEntry);
        }
        if (!nestedMap_.isMutable()) {
          nestedMap_ = nestedMap_.copy();
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return nestedMap_;
      }
      public int getNestedMapCount() {
        return internalGetNestedMap().getMap().size();
      }
      /**
       * <code>map&lt;string, .com.bbrownsound.flink.formats.proto.test.v1.NestedMap&gt; nested_map = 2 [json_name = "nestedMap"];</code>
       */
      @java.lang.Override
      public boolean containsNestedMap(
          java.lang.String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        return internalGetNestedMap().getMap().containsKey(key);
      }
      /**
       * Use {@link #getNestedMapMap()} instead.
       */
      @java.lang.Override
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, com.bbrownsound.flink.formats.proto.test.v1.TestMap.NestedMap> getNestedMap() {
        return getNestedMapMap();
      }
      /**
       * <code>map&lt;string, .com.bbrownsound.flink.formats.proto.test.v1.NestedMap&gt; nested_map = 2 [json_name = "nestedMap"];</code>
       */
      @java.lang.Override
      public java.util.Map<java.lang.String, com.bbrownsound.flink.formats.proto.test.v1.TestMap.NestedMap> getNestedMapMap() {
        return internalGetNestedMap().getMap();
      }
      /**
       * <code>map&lt;string, .com.bbrownsound.flink.formats.proto.test.v1.NestedMap&gt; nested_map = 2 [json_name = "nestedMap"];</code>
       */
      @java.lang.Override
      public /* nullable */
com.bbrownsound.flink.formats.proto.test.v1.TestMap.NestedMap getNestedMapOrDefault(
          java.lang.String key,
          /* nullable */
com.bbrownsound.flink.formats.proto.test.v1.TestMap.NestedMap defaultValue) {
        if (key == null) { throw new NullPointerException("map key"); }
        java.util.Map<java.lang.String, com.bbrownsound.flink.formats.proto.test.v1.TestMap.NestedMap> map =
            internalGetNestedMap().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, .com.bbrownsound.flink.formats.proto.test.v1.NestedMap&gt; nested_map = 2 [json_name = "nestedMap"];</code>
       */
      @java.lang.Override
      public com.bbrownsound.flink.formats.proto.test.v1.TestMap.NestedMap getNestedMapOrThrow(
          java.lang.String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        java.util.Map<java.lang.String, com.bbrownsound.flink.formats.proto.test.v1.TestMap.NestedMap> map =
            internalGetNestedMap().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }
      public Builder clearNestedMap() {
        bitField0_ = (bitField0_ & ~0x00000002);
        internalGetMutableNestedMap().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;string, .com.bbrownsound.flink.formats.proto.test.v1.NestedMap&gt; nested_map = 2 [json_name = "nestedMap"];</code>
       */
      public Builder removeNestedMap(
          java.lang.String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        internalGetMutableNestedMap().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, com.bbrownsound.flink.formats.proto.test.v1.TestMap.NestedMap>
          getMutableNestedMap() {
        bitField0_ |= 0x00000002;
        return internalGetMutableNestedMap().getMutableMap();
      }
      /**
       * <code>map&lt;string, .com.bbrownsound.flink.formats.proto.test.v1.NestedMap&gt; nested_map = 2 [json_name = "nestedMap"];</code>
       */
      public Builder putNestedMap(
          java.lang.String key,
          com.bbrownsound.flink.formats.proto.test.v1.TestMap.NestedMap value) {
        if (key == null) { throw new NullPointerException("map key"); }
        if (value == null) { throw new NullPointerException("map value"); }
        internalGetMutableNestedMap().getMutableMap()
            .put(key, value);
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>map&lt;string, .com.bbrownsound.flink.formats.proto.test.v1.NestedMap&gt; nested_map = 2 [json_name = "nestedMap"];</code>
       */
      public Builder putAllNestedMap(
          java.util.Map<java.lang.String, com.bbrownsound.flink.formats.proto.test.v1.TestMap.NestedMap> values) {
        internalGetMutableNestedMap().getMutableMap()
            .putAll(values);
        bitField0_ |= 0x00000002;
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.bbrownsound.flink.formats.proto.test.v1.MapTest)
    }

    // @@protoc_insertion_point(class_scope:com.bbrownsound.flink.formats.proto.test.v1.MapTest)
    private static final com.bbrownsound.flink.formats.proto.test.v1.TestMap.MapTest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.bbrownsound.flink.formats.proto.test.v1.TestMap.MapTest();
    }

    public static com.bbrownsound.flink.formats.proto.test.v1.TestMap.MapTest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MapTest>
        PARSER = new com.google.protobuf.AbstractParser<MapTest>() {
      @java.lang.Override
      public MapTest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<MapTest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MapTest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.bbrownsound.flink.formats.proto.test.v1.TestMap.MapTest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_bbrownsound_flink_formats_proto_test_v1_NestedMap_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_bbrownsound_flink_formats_proto_test_v1_NestedMap_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_bbrownsound_flink_formats_proto_test_v1_MapTest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_bbrownsound_flink_formats_proto_test_v1_MapTest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_bbrownsound_flink_formats_proto_test_v1_MapTest_SimpleStringMapEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_bbrownsound_flink_formats_proto_test_v1_MapTest_SimpleStringMapEntry_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_bbrownsound_flink_formats_proto_test_v1_MapTest_NestedMapEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_bbrownsound_flink_formats_proto_test_v1_MapTest_NestedMapEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n:com/bbrownsound/flink/formats/proto/te" +
      "st/v1/test_map.proto\022+com.bbrownsound.fl" +
      "ink.formats.proto.test.v1\"\033\n\tNestedMap\022\016" +
      "\n\002id\030\001 \001(\tR\002id\"\236\003\n\007MapTest\022u\n\021simple_str" +
      "ing_map\030\001 \003(\0132I.com.bbrownsound.flink.fo" +
      "rmats.proto.test.v1.MapTest.SimpleString" +
      "MapEntryR\017simpleStringMap\022b\n\nnested_map\030" +
      "\002 \003(\0132C.com.bbrownsound.flink.formats.pr" +
      "oto.test.v1.MapTest.NestedMapEntryR\tnest" +
      "edMap\032B\n\024SimpleStringMapEntry\022\020\n\003key\030\001 \001" +
      "(\tR\003key\022\024\n\005value\030\002 \001(\tR\005value:\0028\001\032t\n\016Nes" +
      "tedMapEntry\022\020\n\003key\030\001 \001(\tR\003key\022L\n\005value\030\002" +
      " \001(\01326.com.bbrownsound.flink.formats.pro" +
      "to.test.v1.NestedMapR\005value:\0028\001B-\n+com.b" +
      "brownsound.flink.formats.proto.test.v1b\006" +
      "proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_bbrownsound_flink_formats_proto_test_v1_NestedMap_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_bbrownsound_flink_formats_proto_test_v1_NestedMap_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_bbrownsound_flink_formats_proto_test_v1_NestedMap_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_com_bbrownsound_flink_formats_proto_test_v1_MapTest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_bbrownsound_flink_formats_proto_test_v1_MapTest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_bbrownsound_flink_formats_proto_test_v1_MapTest_descriptor,
        new java.lang.String[] { "SimpleStringMap", "NestedMap", });
    internal_static_com_bbrownsound_flink_formats_proto_test_v1_MapTest_SimpleStringMapEntry_descriptor =
      internal_static_com_bbrownsound_flink_formats_proto_test_v1_MapTest_descriptor.getNestedTypes().get(0);
    internal_static_com_bbrownsound_flink_formats_proto_test_v1_MapTest_SimpleStringMapEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_bbrownsound_flink_formats_proto_test_v1_MapTest_SimpleStringMapEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_com_bbrownsound_flink_formats_proto_test_v1_MapTest_NestedMapEntry_descriptor =
      internal_static_com_bbrownsound_flink_formats_proto_test_v1_MapTest_descriptor.getNestedTypes().get(1);
    internal_static_com_bbrownsound_flink_formats_proto_test_v1_MapTest_NestedMapEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_bbrownsound_flink_formats_proto_test_v1_MapTest_NestedMapEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
