// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/bbrownsound/flink/formats/proto/test/v1/test_oneof.proto

package com.bbrownsound.flink.formats.proto.test.v1;

public final class TestOneof {
  private TestOneof() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MessageWithOneofOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.bbrownsound.flink.formats.proto.test.v1.MessageWithOneof)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 a = 1 [json_name = "a"];</code>
     * @return Whether the a field is set.
     */
    boolean hasA();
    /**
     * <code>int32 a = 1 [json_name = "a"];</code>
     * @return The a.
     */
    int getA();

    /**
     * <code>string b = 2 [json_name = "b"];</code>
     * @return Whether the b field is set.
     */
    boolean hasB();
    /**
     * <code>string b = 2 [json_name = "b"];</code>
     * @return The b.
     */
    java.lang.String getB();
    /**
     * <code>string b = 2 [json_name = "b"];</code>
     * @return The bytes for b.
     */
    com.google.protobuf.ByteString
        getBBytes();

    com.bbrownsound.flink.formats.proto.test.v1.TestOneof.MessageWithOneof.ChoiceCase getChoiceCase();
  }
  /**
   * <pre>
   * Message with a oneof to exercise oneof code paths in serialize/deserialize converters.
   * </pre>
   *
   * Protobuf type {@code com.bbrownsound.flink.formats.proto.test.v1.MessageWithOneof}
   */
  public static final class MessageWithOneof extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.bbrownsound.flink.formats.proto.test.v1.MessageWithOneof)
      MessageWithOneofOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MessageWithOneof.newBuilder() to construct.
    private MessageWithOneof(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MessageWithOneof() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new MessageWithOneof();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bbrownsound.flink.formats.proto.test.v1.TestOneof.internal_static_com_bbrownsound_flink_formats_proto_test_v1_MessageWithOneof_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bbrownsound.flink.formats.proto.test.v1.TestOneof.internal_static_com_bbrownsound_flink_formats_proto_test_v1_MessageWithOneof_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.bbrownsound.flink.formats.proto.test.v1.TestOneof.MessageWithOneof.class, com.bbrownsound.flink.formats.proto.test.v1.TestOneof.MessageWithOneof.Builder.class);
    }

    private int choiceCase_ = 0;
    @SuppressWarnings("serial")
    private java.lang.Object choice_;
    public enum ChoiceCase
        implements com.google.protobuf.Internal.EnumLite,
            com.google.protobuf.AbstractMessage.InternalOneOfEnum {
      A(1),
      B(2),
      CHOICE_NOT_SET(0);
      private final int value;
      private ChoiceCase(int value) {
        this.value = value;
      }
      /**
       * @param value The number of the enum to look for.
       * @return The enum associated with the given number.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static ChoiceCase valueOf(int value) {
        return forNumber(value);
      }

      public static ChoiceCase forNumber(int value) {
        switch (value) {
          case 1: return A;
          case 2: return B;
          case 0: return CHOICE_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public ChoiceCase
    getChoiceCase() {
      return ChoiceCase.forNumber(
          choiceCase_);
    }

    public static final int A_FIELD_NUMBER = 1;
    /**
     * <code>int32 a = 1 [json_name = "a"];</code>
     * @return Whether the a field is set.
     */
    @java.lang.Override
    public boolean hasA() {
      return choiceCase_ == 1;
    }
    /**
     * <code>int32 a = 1 [json_name = "a"];</code>
     * @return The a.
     */
    @java.lang.Override
    public int getA() {
      if (choiceCase_ == 1) {
        return (java.lang.Integer) choice_;
      }
      return 0;
    }

    public static final int B_FIELD_NUMBER = 2;
    /**
     * <code>string b = 2 [json_name = "b"];</code>
     * @return Whether the b field is set.
     */
    public boolean hasB() {
      return choiceCase_ == 2;
    }
    /**
     * <code>string b = 2 [json_name = "b"];</code>
     * @return The b.
     */
    public java.lang.String getB() {
      java.lang.Object ref = "";
      if (choiceCase_ == 2) {
        ref = choice_;
      }
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (choiceCase_ == 2) {
          choice_ = s;
        }
        return s;
      }
    }
    /**
     * <code>string b = 2 [json_name = "b"];</code>
     * @return The bytes for b.
     */
    public com.google.protobuf.ByteString
        getBBytes() {
      java.lang.Object ref = "";
      if (choiceCase_ == 2) {
        ref = choice_;
      }
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        if (choiceCase_ == 2) {
          choice_ = b;
        }
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (choiceCase_ == 1) {
        output.writeInt32(
            1, (int)((java.lang.Integer) choice_));
      }
      if (choiceCase_ == 2) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, choice_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (choiceCase_ == 1) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(
              1, (int)((java.lang.Integer) choice_));
      }
      if (choiceCase_ == 2) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, choice_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.bbrownsound.flink.formats.proto.test.v1.TestOneof.MessageWithOneof)) {
        return super.equals(obj);
      }
      com.bbrownsound.flink.formats.proto.test.v1.TestOneof.MessageWithOneof other = (com.bbrownsound.flink.formats.proto.test.v1.TestOneof.MessageWithOneof) obj;

      if (!getChoiceCase().equals(other.getChoiceCase())) return false;
      switch (choiceCase_) {
        case 1:
          if (getA()
              != other.getA()) return false;
          break;
        case 2:
          if (!getB()
              .equals(other.getB())) return false;
          break;
        case 0:
        default:
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      switch (choiceCase_) {
        case 1:
          hash = (37 * hash) + A_FIELD_NUMBER;
          hash = (53 * hash) + getA();
          break;
        case 2:
          hash = (37 * hash) + B_FIELD_NUMBER;
          hash = (53 * hash) + getB().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.bbrownsound.flink.formats.proto.test.v1.TestOneof.MessageWithOneof parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bbrownsound.flink.formats.proto.test.v1.TestOneof.MessageWithOneof parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bbrownsound.flink.formats.proto.test.v1.TestOneof.MessageWithOneof parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bbrownsound.flink.formats.proto.test.v1.TestOneof.MessageWithOneof parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bbrownsound.flink.formats.proto.test.v1.TestOneof.MessageWithOneof parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bbrownsound.flink.formats.proto.test.v1.TestOneof.MessageWithOneof parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bbrownsound.flink.formats.proto.test.v1.TestOneof.MessageWithOneof parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.bbrownsound.flink.formats.proto.test.v1.TestOneof.MessageWithOneof parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.bbrownsound.flink.formats.proto.test.v1.TestOneof.MessageWithOneof parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.bbrownsound.flink.formats.proto.test.v1.TestOneof.MessageWithOneof parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.bbrownsound.flink.formats.proto.test.v1.TestOneof.MessageWithOneof parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.bbrownsound.flink.formats.proto.test.v1.TestOneof.MessageWithOneof parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.bbrownsound.flink.formats.proto.test.v1.TestOneof.MessageWithOneof prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Message with a oneof to exercise oneof code paths in serialize/deserialize converters.
     * </pre>
     *
     * Protobuf type {@code com.bbrownsound.flink.formats.proto.test.v1.MessageWithOneof}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.bbrownsound.flink.formats.proto.test.v1.MessageWithOneof)
        com.bbrownsound.flink.formats.proto.test.v1.TestOneof.MessageWithOneofOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.bbrownsound.flink.formats.proto.test.v1.TestOneof.internal_static_com_bbrownsound_flink_formats_proto_test_v1_MessageWithOneof_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.bbrownsound.flink.formats.proto.test.v1.TestOneof.internal_static_com_bbrownsound_flink_formats_proto_test_v1_MessageWithOneof_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.bbrownsound.flink.formats.proto.test.v1.TestOneof.MessageWithOneof.class, com.bbrownsound.flink.formats.proto.test.v1.TestOneof.MessageWithOneof.Builder.class);
      }

      // Construct using com.bbrownsound.flink.formats.proto.test.v1.TestOneof.MessageWithOneof.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        choiceCase_ = 0;
        choice_ = null;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.bbrownsound.flink.formats.proto.test.v1.TestOneof.internal_static_com_bbrownsound_flink_formats_proto_test_v1_MessageWithOneof_descriptor;
      }

      @java.lang.Override
      public com.bbrownsound.flink.formats.proto.test.v1.TestOneof.MessageWithOneof getDefaultInstanceForType() {
        return com.bbrownsound.flink.formats.proto.test.v1.TestOneof.MessageWithOneof.getDefaultInstance();
      }

      @java.lang.Override
      public com.bbrownsound.flink.formats.proto.test.v1.TestOneof.MessageWithOneof build() {
        com.bbrownsound.flink.formats.proto.test.v1.TestOneof.MessageWithOneof result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.bbrownsound.flink.formats.proto.test.v1.TestOneof.MessageWithOneof buildPartial() {
        com.bbrownsound.flink.formats.proto.test.v1.TestOneof.MessageWithOneof result = new com.bbrownsound.flink.formats.proto.test.v1.TestOneof.MessageWithOneof(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        buildPartialOneofs(result);
        onBuilt();
        return result;
      }

      private void buildPartial0(com.bbrownsound.flink.formats.proto.test.v1.TestOneof.MessageWithOneof result) {
        int from_bitField0_ = bitField0_;
      }

      private void buildPartialOneofs(com.bbrownsound.flink.formats.proto.test.v1.TestOneof.MessageWithOneof result) {
        result.choiceCase_ = choiceCase_;
        result.choice_ = this.choice_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.bbrownsound.flink.formats.proto.test.v1.TestOneof.MessageWithOneof) {
          return mergeFrom((com.bbrownsound.flink.formats.proto.test.v1.TestOneof.MessageWithOneof)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.bbrownsound.flink.formats.proto.test.v1.TestOneof.MessageWithOneof other) {
        if (other == com.bbrownsound.flink.formats.proto.test.v1.TestOneof.MessageWithOneof.getDefaultInstance()) return this;
        switch (other.getChoiceCase()) {
          case A: {
            setA(other.getA());
            break;
          }
          case B: {
            choiceCase_ = 2;
            choice_ = other.choice_;
            onChanged();
            break;
          }
          case CHOICE_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                choice_ = input.readInt32();
                choiceCase_ = 1;
                break;
              } // case 8
              case 18: {
                java.lang.String s = input.readStringRequireUtf8();
                choiceCase_ = 2;
                choice_ = s;
                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int choiceCase_ = 0;
      private java.lang.Object choice_;
      public ChoiceCase
          getChoiceCase() {
        return ChoiceCase.forNumber(
            choiceCase_);
      }

      public Builder clearChoice() {
        choiceCase_ = 0;
        choice_ = null;
        onChanged();
        return this;
      }

      private int bitField0_;

      /**
       * <code>int32 a = 1 [json_name = "a"];</code>
       * @return Whether the a field is set.
       */
      public boolean hasA() {
        return choiceCase_ == 1;
      }
      /**
       * <code>int32 a = 1 [json_name = "a"];</code>
       * @return The a.
       */
      public int getA() {
        if (choiceCase_ == 1) {
          return (java.lang.Integer) choice_;
        }
        return 0;
      }
      /**
       * <code>int32 a = 1 [json_name = "a"];</code>
       * @param value The a to set.
       * @return This builder for chaining.
       */
      public Builder setA(int value) {

        choiceCase_ = 1;
        choice_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 a = 1 [json_name = "a"];</code>
       * @return This builder for chaining.
       */
      public Builder clearA() {
        if (choiceCase_ == 1) {
          choiceCase_ = 0;
          choice_ = null;
          onChanged();
        }
        return this;
      }

      /**
       * <code>string b = 2 [json_name = "b"];</code>
       * @return Whether the b field is set.
       */
      @java.lang.Override
      public boolean hasB() {
        return choiceCase_ == 2;
      }
      /**
       * <code>string b = 2 [json_name = "b"];</code>
       * @return The b.
       */
      @java.lang.Override
      public java.lang.String getB() {
        java.lang.Object ref = "";
        if (choiceCase_ == 2) {
          ref = choice_;
        }
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (choiceCase_ == 2) {
            choice_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string b = 2 [json_name = "b"];</code>
       * @return The bytes for b.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getBBytes() {
        java.lang.Object ref = "";
        if (choiceCase_ == 2) {
          ref = choice_;
        }
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          if (choiceCase_ == 2) {
            choice_ = b;
          }
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string b = 2 [json_name = "b"];</code>
       * @param value The b to set.
       * @return This builder for chaining.
       */
      public Builder setB(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        choiceCase_ = 2;
        choice_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string b = 2 [json_name = "b"];</code>
       * @return This builder for chaining.
       */
      public Builder clearB() {
        if (choiceCase_ == 2) {
          choiceCase_ = 0;
          choice_ = null;
          onChanged();
        }
        return this;
      }
      /**
       * <code>string b = 2 [json_name = "b"];</code>
       * @param value The bytes for b to set.
       * @return This builder for chaining.
       */
      public Builder setBBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        choiceCase_ = 2;
        choice_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.bbrownsound.flink.formats.proto.test.v1.MessageWithOneof)
    }

    // @@protoc_insertion_point(class_scope:com.bbrownsound.flink.formats.proto.test.v1.MessageWithOneof)
    private static final com.bbrownsound.flink.formats.proto.test.v1.TestOneof.MessageWithOneof DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.bbrownsound.flink.formats.proto.test.v1.TestOneof.MessageWithOneof();
    }

    public static com.bbrownsound.flink.formats.proto.test.v1.TestOneof.MessageWithOneof getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MessageWithOneof>
        PARSER = new com.google.protobuf.AbstractParser<MessageWithOneof>() {
      @java.lang.Override
      public MessageWithOneof parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<MessageWithOneof> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MessageWithOneof> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.bbrownsound.flink.formats.proto.test.v1.TestOneof.MessageWithOneof getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_bbrownsound_flink_formats_proto_test_v1_MessageWithOneof_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_bbrownsound_flink_formats_proto_test_v1_MessageWithOneof_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n<com/bbrownsound/flink/formats/proto/te" +
      "st/v1/test_oneof.proto\022+com.bbrownsound." +
      "flink.formats.proto.test.v1\"<\n\020MessageWi" +
      "thOneof\022\016\n\001a\030\001 \001(\005H\000R\001a\022\016\n\001b\030\002 \001(\tH\000R\001bB" +
      "\010\n\006choiceB-\n+com.bbrownsound.flink.forma" +
      "ts.proto.test.v1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_bbrownsound_flink_formats_proto_test_v1_MessageWithOneof_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_bbrownsound_flink_formats_proto_test_v1_MessageWithOneof_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_bbrownsound_flink_formats_proto_test_v1_MessageWithOneof_descriptor,
        new java.lang.String[] { "A", "B", "Choice", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
