// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/bbrownsound/flink/formats/proto/test/v1/test_enums.proto

package com.bbrownsound.flink.formats.proto.test.v1;

public final class TestEnums {
  private TestEnums() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code com.bbrownsound.flink.formats.proto.test.v1.MessageType}
   */
  public enum MessageType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>TEXT = 0;</code>
     */
    TEXT(0),
    /**
     * <code>IMAGE = 1;</code>
     */
    IMAGE(1),
    /**
     * <code>VIDEO = 2;</code>
     */
    VIDEO(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>TEXT = 0;</code>
     */
    public static final int TEXT_VALUE = 0;
    /**
     * <code>IMAGE = 1;</code>
     */
    public static final int IMAGE_VALUE = 1;
    /**
     * <code>VIDEO = 2;</code>
     */
    public static final int VIDEO_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static MessageType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static MessageType forNumber(int value) {
      switch (value) {
        case 0: return TEXT;
        case 1: return IMAGE;
        case 2: return VIDEO;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<MessageType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        MessageType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<MessageType>() {
            public MessageType findValueByNumber(int number) {
              return MessageType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.bbrownsound.flink.formats.proto.test.v1.TestEnums.getDescriptor().getEnumTypes().get(0);
    }

    private static final MessageType[] VALUES = values();

    public static MessageType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private MessageType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.bbrownsound.flink.formats.proto.test.v1.MessageType)
  }

  /**
   * Protobuf enum {@code com.bbrownsound.flink.formats.proto.test.v1.MessageStatus}
   */
  public enum MessageStatus
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>SENT = 0;</code>
     */
    SENT(0),
    /**
     * <code>RECEIVED = 1;</code>
     */
    RECEIVED(1),
    /**
     * <code>READ = 2;</code>
     */
    READ(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>SENT = 0;</code>
     */
    public static final int SENT_VALUE = 0;
    /**
     * <code>RECEIVED = 1;</code>
     */
    public static final int RECEIVED_VALUE = 1;
    /**
     * <code>READ = 2;</code>
     */
    public static final int READ_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static MessageStatus valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static MessageStatus forNumber(int value) {
      switch (value) {
        case 0: return SENT;
        case 1: return RECEIVED;
        case 2: return READ;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<MessageStatus>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        MessageStatus> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<MessageStatus>() {
            public MessageStatus findValueByNumber(int number) {
              return MessageStatus.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.bbrownsound.flink.formats.proto.test.v1.TestEnums.getDescriptor().getEnumTypes().get(1);
    }

    private static final MessageStatus[] VALUES = values();

    public static MessageStatus valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private MessageStatus(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.bbrownsound.flink.formats.proto.test.v1.MessageStatus)
  }

  public interface TestEnumOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.bbrownsound.flink.formats.proto.test.v1.TestEnum)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.com.bbrownsound.flink.formats.proto.test.v1.MessageType type = 1 [json_name = "type"];</code>
     * @return The enum numeric value on the wire for type.
     */
    int getTypeValue();
    /**
     * <code>.com.bbrownsound.flink.formats.proto.test.v1.MessageType type = 1 [json_name = "type"];</code>
     * @return The type.
     */
    com.bbrownsound.flink.formats.proto.test.v1.TestEnums.MessageType getType();

    /**
     * <code>repeated .com.bbrownsound.flink.formats.proto.test.v1.MessageStatus status = 2 [json_name = "status"];</code>
     * @return A list containing the status.
     */
    java.util.List<com.bbrownsound.flink.formats.proto.test.v1.TestEnums.MessageStatus> getStatusList();
    /**
     * <code>repeated .com.bbrownsound.flink.formats.proto.test.v1.MessageStatus status = 2 [json_name = "status"];</code>
     * @return The count of status.
     */
    int getStatusCount();
    /**
     * <code>repeated .com.bbrownsound.flink.formats.proto.test.v1.MessageStatus status = 2 [json_name = "status"];</code>
     * @param index The index of the element to return.
     * @return The status at the given index.
     */
    com.bbrownsound.flink.formats.proto.test.v1.TestEnums.MessageStatus getStatus(int index);
    /**
     * <code>repeated .com.bbrownsound.flink.formats.proto.test.v1.MessageStatus status = 2 [json_name = "status"];</code>
     * @return A list containing the enum numeric values on the wire for status.
     */
    java.util.List<java.lang.Integer>
    getStatusValueList();
    /**
     * <code>repeated .com.bbrownsound.flink.formats.proto.test.v1.MessageStatus status = 2 [json_name = "status"];</code>
     * @param index The index of the value to return.
     * @return The enum numeric value on the wire of status at the given index.
     */
    int getStatusValue(int index);

    /**
     * <code>map&lt;string, .com.bbrownsound.flink.formats.proto.test.v1.MessageStatus&gt; statusMap = 3 [json_name = "statusMap"];</code>
     */
    int getStatusMapCount();
    /**
     * <code>map&lt;string, .com.bbrownsound.flink.formats.proto.test.v1.MessageStatus&gt; statusMap = 3 [json_name = "statusMap"];</code>
     */
    boolean containsStatusMap(
        java.lang.String key);
    /**
     * Use {@link #getStatusMapMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, com.bbrownsound.flink.formats.proto.test.v1.TestEnums.MessageStatus>
    getStatusMap();
    /**
     * <code>map&lt;string, .com.bbrownsound.flink.formats.proto.test.v1.MessageStatus&gt; statusMap = 3 [json_name = "statusMap"];</code>
     */
    java.util.Map<java.lang.String, com.bbrownsound.flink.formats.proto.test.v1.TestEnums.MessageStatus>
    getStatusMapMap();
    /**
     * <code>map&lt;string, .com.bbrownsound.flink.formats.proto.test.v1.MessageStatus&gt; statusMap = 3 [json_name = "statusMap"];</code>
     */
    /* nullable */
com.bbrownsound.flink.formats.proto.test.v1.TestEnums.MessageStatus getStatusMapOrDefault(
        java.lang.String key,
        /* nullable */
com.bbrownsound.flink.formats.proto.test.v1.TestEnums.MessageStatus         defaultValue);
    /**
     * <code>map&lt;string, .com.bbrownsound.flink.formats.proto.test.v1.MessageStatus&gt; statusMap = 3 [json_name = "statusMap"];</code>
     */
    com.bbrownsound.flink.formats.proto.test.v1.TestEnums.MessageStatus getStatusMapOrThrow(
        java.lang.String key);
    /**
     * Use {@link #getStatusMapValueMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, java.lang.Integer>
    getStatusMapValue();
    /**
     * <code>map&lt;string, .com.bbrownsound.flink.formats.proto.test.v1.MessageStatus&gt; statusMap = 3 [json_name = "statusMap"];</code>
     */
    java.util.Map<java.lang.String, java.lang.Integer>
    getStatusMapValueMap();
    /**
     * <code>map&lt;string, .com.bbrownsound.flink.formats.proto.test.v1.MessageStatus&gt; statusMap = 3 [json_name = "statusMap"];</code>
     */
    int getStatusMapValueOrDefault(
        java.lang.String key,
        int defaultValue);
    /**
     * <code>map&lt;string, .com.bbrownsound.flink.formats.proto.test.v1.MessageStatus&gt; statusMap = 3 [json_name = "statusMap"];</code>
     */
    int getStatusMapValueOrThrow(
        java.lang.String key);
  }
  /**
   * Protobuf type {@code com.bbrownsound.flink.formats.proto.test.v1.TestEnum}
   */
  public static final class TestEnum extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.bbrownsound.flink.formats.proto.test.v1.TestEnum)
      TestEnumOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TestEnum.newBuilder() to construct.
    private TestEnum(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TestEnum() {
      type_ = 0;
      status_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new TestEnum();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bbrownsound.flink.formats.proto.test.v1.TestEnums.internal_static_com_bbrownsound_flink_formats_proto_test_v1_TestEnum_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @java.lang.Override
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 3:
          return internalGetStatusMap();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bbrownsound.flink.formats.proto.test.v1.TestEnums.internal_static_com_bbrownsound_flink_formats_proto_test_v1_TestEnum_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.bbrownsound.flink.formats.proto.test.v1.TestEnums.TestEnum.class, com.bbrownsound.flink.formats.proto.test.v1.TestEnums.TestEnum.Builder.class);
    }

    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_ = 0;
    /**
     * <code>.com.bbrownsound.flink.formats.proto.test.v1.MessageType type = 1 [json_name = "type"];</code>
     * @return The enum numeric value on the wire for type.
     */
    @java.lang.Override public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.com.bbrownsound.flink.formats.proto.test.v1.MessageType type = 1 [json_name = "type"];</code>
     * @return The type.
     */
    @java.lang.Override public com.bbrownsound.flink.formats.proto.test.v1.TestEnums.MessageType getType() {
      com.bbrownsound.flink.formats.proto.test.v1.TestEnums.MessageType result = com.bbrownsound.flink.formats.proto.test.v1.TestEnums.MessageType.forNumber(type_);
      return result == null ? com.bbrownsound.flink.formats.proto.test.v1.TestEnums.MessageType.UNRECOGNIZED : result;
    }

    public static final int STATUS_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private java.util.List<java.lang.Integer> status_;
    private static final com.google.protobuf.Internal.ListAdapter.Converter<
        java.lang.Integer, com.bbrownsound.flink.formats.proto.test.v1.TestEnums.MessageStatus> status_converter_ =
            new com.google.protobuf.Internal.ListAdapter.Converter<
                java.lang.Integer, com.bbrownsound.flink.formats.proto.test.v1.TestEnums.MessageStatus>() {
              public com.bbrownsound.flink.formats.proto.test.v1.TestEnums.MessageStatus convert(java.lang.Integer from) {
                com.bbrownsound.flink.formats.proto.test.v1.TestEnums.MessageStatus result = com.bbrownsound.flink.formats.proto.test.v1.TestEnums.MessageStatus.forNumber(from);
                return result == null ? com.bbrownsound.flink.formats.proto.test.v1.TestEnums.MessageStatus.UNRECOGNIZED : result;
              }
            };
    /**
     * <code>repeated .com.bbrownsound.flink.formats.proto.test.v1.MessageStatus status = 2 [json_name = "status"];</code>
     * @return A list containing the status.
     */
    @java.lang.Override
    public java.util.List<com.bbrownsound.flink.formats.proto.test.v1.TestEnums.MessageStatus> getStatusList() {
      return new com.google.protobuf.Internal.ListAdapter<
          java.lang.Integer, com.bbrownsound.flink.formats.proto.test.v1.TestEnums.MessageStatus>(status_, status_converter_);
    }
    /**
     * <code>repeated .com.bbrownsound.flink.formats.proto.test.v1.MessageStatus status = 2 [json_name = "status"];</code>
     * @return The count of status.
     */
    @java.lang.Override
    public int getStatusCount() {
      return status_.size();
    }
    /**
     * <code>repeated .com.bbrownsound.flink.formats.proto.test.v1.MessageStatus status = 2 [json_name = "status"];</code>
     * @param index The index of the element to return.
     * @return The status at the given index.
     */
    @java.lang.Override
    public com.bbrownsound.flink.formats.proto.test.v1.TestEnums.MessageStatus getStatus(int index) {
      return status_converter_.convert(status_.get(index));
    }
    /**
     * <code>repeated .com.bbrownsound.flink.formats.proto.test.v1.MessageStatus status = 2 [json_name = "status"];</code>
     * @return A list containing the enum numeric values on the wire for status.
     */
    @java.lang.Override
    public java.util.List<java.lang.Integer>
    getStatusValueList() {
      return status_;
    }
    /**
     * <code>repeated .com.bbrownsound.flink.formats.proto.test.v1.MessageStatus status = 2 [json_name = "status"];</code>
     * @param index The index of the value to return.
     * @return The enum numeric value on the wire of status at the given index.
     */
    @java.lang.Override
    public int getStatusValue(int index) {
      return status_.get(index);
    }
    private int statusMemoizedSerializedSize;

    public static final int STATUSMAP_FIELD_NUMBER = 3;
    private static final class StatusMapDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, java.lang.Integer> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, java.lang.Integer>newDefaultInstance(
                  com.bbrownsound.flink.formats.proto.test.v1.TestEnums.internal_static_com_bbrownsound_flink_formats_proto_test_v1_TestEnum_StatusMapEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.ENUM,
                  com.bbrownsound.flink.formats.proto.test.v1.TestEnums.MessageStatus.SENT.getNumber());
    }
    @SuppressWarnings("serial")
    private com.google.protobuf.MapField<
        java.lang.String, java.lang.Integer> statusMap_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.Integer>
    internalGetStatusMap() {
      if (statusMap_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            StatusMapDefaultEntryHolder.defaultEntry);
      }
      return statusMap_;
    }
    private static final
    com.google.protobuf.Internal.MapAdapter.Converter<
        java.lang.Integer, com.bbrownsound.flink.formats.proto.test.v1.TestEnums.MessageStatus> statusMapValueConverter =
            com.google.protobuf.Internal.MapAdapter.newEnumConverter(
                com.bbrownsound.flink.formats.proto.test.v1.TestEnums.MessageStatus.internalGetValueMap(),
                com.bbrownsound.flink.formats.proto.test.v1.TestEnums.MessageStatus.UNRECOGNIZED);
    private static final java.util.Map<java.lang.String, com.bbrownsound.flink.formats.proto.test.v1.TestEnums.MessageStatus>
    internalGetAdaptedStatusMapMap(
        java.util.Map<java.lang.String, java.lang.Integer> map) {
      return new com.google.protobuf.Internal.MapAdapter<
          java.lang.String, com.bbrownsound.flink.formats.proto.test.v1.TestEnums.MessageStatus, java.lang.Integer>(
              map, statusMapValueConverter);
    }
    public int getStatusMapCount() {
      return internalGetStatusMap().getMap().size();
    }
    /**
     * <code>map&lt;string, .com.bbrownsound.flink.formats.proto.test.v1.MessageStatus&gt; statusMap = 3 [json_name = "statusMap"];</code>
     */
    @java.lang.Override
    public boolean containsStatusMap(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetStatusMap().getMap().containsKey(key);
    }
    /**
     * Use {@link #getStatusMapMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, com.bbrownsound.flink.formats.proto.test.v1.TestEnums.MessageStatus>
    getStatusMap() {
      return getStatusMapMap();
    }
    /**
     * <code>map&lt;string, .com.bbrownsound.flink.formats.proto.test.v1.MessageStatus&gt; statusMap = 3 [json_name = "statusMap"];</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.String, com.bbrownsound.flink.formats.proto.test.v1.TestEnums.MessageStatus>
    getStatusMapMap() {
      return internalGetAdaptedStatusMapMap(
          internalGetStatusMap().getMap());}
    /**
     * <code>map&lt;string, .com.bbrownsound.flink.formats.proto.test.v1.MessageStatus&gt; statusMap = 3 [json_name = "statusMap"];</code>
     */
    @java.lang.Override
    public /* nullable */
com.bbrownsound.flink.formats.proto.test.v1.TestEnums.MessageStatus getStatusMapOrDefault(
        java.lang.String key,
        /* nullable */
com.bbrownsound.flink.formats.proto.test.v1.TestEnums.MessageStatus defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.Integer> map =
          internalGetStatusMap().getMap();
      return map.containsKey(key)
             ? statusMapValueConverter.doForward(map.get(key))
             : defaultValue;
    }
    /**
     * <code>map&lt;string, .com.bbrownsound.flink.formats.proto.test.v1.MessageStatus&gt; statusMap = 3 [json_name = "statusMap"];</code>
     */
    @java.lang.Override
    public com.bbrownsound.flink.formats.proto.test.v1.TestEnums.MessageStatus getStatusMapOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.Integer> map =
          internalGetStatusMap().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return statusMapValueConverter.doForward(map.get(key));
    }
    /**
     * Use {@link #getStatusMapValueMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.Integer>
    getStatusMapValue() {
      return getStatusMapValueMap();
    }
    /**
     * <code>map&lt;string, .com.bbrownsound.flink.formats.proto.test.v1.MessageStatus&gt; statusMap = 3 [json_name = "statusMap"];</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.String, java.lang.Integer>
    getStatusMapValueMap() {
      return internalGetStatusMap().getMap();
    }
    /**
     * <code>map&lt;string, .com.bbrownsound.flink.formats.proto.test.v1.MessageStatus&gt; statusMap = 3 [json_name = "statusMap"];</code>
     */
    @java.lang.Override
    public int getStatusMapValueOrDefault(
        java.lang.String key,
        int defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.Integer> map =
          internalGetStatusMap().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, .com.bbrownsound.flink.formats.proto.test.v1.MessageStatus&gt; statusMap = 3 [json_name = "statusMap"];</code>
     */
    @java.lang.Override
    public int getStatusMapValueOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, java.lang.Integer> map =
          internalGetStatusMap().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (type_ != com.bbrownsound.flink.formats.proto.test.v1.TestEnums.MessageType.TEXT.getNumber()) {
        output.writeEnum(1, type_);
      }
      if (getStatusList().size() > 0) {
        output.writeUInt32NoTag(18);
        output.writeUInt32NoTag(statusMemoizedSerializedSize);
      }
      for (int i = 0; i < status_.size(); i++) {
        output.writeEnumNoTag(status_.get(i));
      }
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetStatusMap(),
          StatusMapDefaultEntryHolder.defaultEntry,
          3);
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (type_ != com.bbrownsound.flink.formats.proto.test.v1.TestEnums.MessageType.TEXT.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < status_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeEnumSizeNoTag(status_.get(i));
        }
        size += dataSize;
        if (!getStatusList().isEmpty()) {  size += 1;
          size += com.google.protobuf.CodedOutputStream
            .computeUInt32SizeNoTag(dataSize);
        }statusMemoizedSerializedSize = dataSize;
      }
      for (java.util.Map.Entry<java.lang.String, java.lang.Integer> entry
           : internalGetStatusMap().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, java.lang.Integer>
        statusMap__ = StatusMapDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(3, statusMap__);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.bbrownsound.flink.formats.proto.test.v1.TestEnums.TestEnum)) {
        return super.equals(obj);
      }
      com.bbrownsound.flink.formats.proto.test.v1.TestEnums.TestEnum other = (com.bbrownsound.flink.formats.proto.test.v1.TestEnums.TestEnum) obj;

      if (type_ != other.type_) return false;
      if (!status_.equals(other.status_)) return false;
      if (!internalGetStatusMap().equals(
          other.internalGetStatusMap())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      if (getStatusCount() > 0) {
        hash = (37 * hash) + STATUS_FIELD_NUMBER;
        hash = (53 * hash) + status_.hashCode();
      }
      if (!internalGetStatusMap().getMap().isEmpty()) {
        hash = (37 * hash) + STATUSMAP_FIELD_NUMBER;
        hash = (53 * hash) + internalGetStatusMap().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.bbrownsound.flink.formats.proto.test.v1.TestEnums.TestEnum parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bbrownsound.flink.formats.proto.test.v1.TestEnums.TestEnum parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bbrownsound.flink.formats.proto.test.v1.TestEnums.TestEnum parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bbrownsound.flink.formats.proto.test.v1.TestEnums.TestEnum parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bbrownsound.flink.formats.proto.test.v1.TestEnums.TestEnum parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bbrownsound.flink.formats.proto.test.v1.TestEnums.TestEnum parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bbrownsound.flink.formats.proto.test.v1.TestEnums.TestEnum parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.bbrownsound.flink.formats.proto.test.v1.TestEnums.TestEnum parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.bbrownsound.flink.formats.proto.test.v1.TestEnums.TestEnum parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.bbrownsound.flink.formats.proto.test.v1.TestEnums.TestEnum parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.bbrownsound.flink.formats.proto.test.v1.TestEnums.TestEnum parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.bbrownsound.flink.formats.proto.test.v1.TestEnums.TestEnum parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.bbrownsound.flink.formats.proto.test.v1.TestEnums.TestEnum prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.bbrownsound.flink.formats.proto.test.v1.TestEnum}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.bbrownsound.flink.formats.proto.test.v1.TestEnum)
        com.bbrownsound.flink.formats.proto.test.v1.TestEnums.TestEnumOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.bbrownsound.flink.formats.proto.test.v1.TestEnums.internal_static_com_bbrownsound_flink_formats_proto_test_v1_TestEnum_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 3:
            return internalGetStatusMap();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 3:
            return internalGetMutableStatusMap();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.bbrownsound.flink.formats.proto.test.v1.TestEnums.internal_static_com_bbrownsound_flink_formats_proto_test_v1_TestEnum_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.bbrownsound.flink.formats.proto.test.v1.TestEnums.TestEnum.class, com.bbrownsound.flink.formats.proto.test.v1.TestEnums.TestEnum.Builder.class);
      }

      // Construct using com.bbrownsound.flink.formats.proto.test.v1.TestEnums.TestEnum.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        type_ = 0;
        status_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        internalGetMutableStatusMap().clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.bbrownsound.flink.formats.proto.test.v1.TestEnums.internal_static_com_bbrownsound_flink_formats_proto_test_v1_TestEnum_descriptor;
      }

      @java.lang.Override
      public com.bbrownsound.flink.formats.proto.test.v1.TestEnums.TestEnum getDefaultInstanceForType() {
        return com.bbrownsound.flink.formats.proto.test.v1.TestEnums.TestEnum.getDefaultInstance();
      }

      @java.lang.Override
      public com.bbrownsound.flink.formats.proto.test.v1.TestEnums.TestEnum build() {
        com.bbrownsound.flink.formats.proto.test.v1.TestEnums.TestEnum result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.bbrownsound.flink.formats.proto.test.v1.TestEnums.TestEnum buildPartial() {
        com.bbrownsound.flink.formats.proto.test.v1.TestEnums.TestEnum result = new com.bbrownsound.flink.formats.proto.test.v1.TestEnums.TestEnum(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(com.bbrownsound.flink.formats.proto.test.v1.TestEnums.TestEnum result) {
        if (((bitField0_ & 0x00000002) != 0)) {
          status_ = java.util.Collections.unmodifiableList(status_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.status_ = status_;
      }

      private void buildPartial0(com.bbrownsound.flink.formats.proto.test.v1.TestEnums.TestEnum result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.type_ = type_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.statusMap_ = internalGetStatusMap();
          result.statusMap_.makeImmutable();
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.bbrownsound.flink.formats.proto.test.v1.TestEnums.TestEnum) {
          return mergeFrom((com.bbrownsound.flink.formats.proto.test.v1.TestEnums.TestEnum)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.bbrownsound.flink.formats.proto.test.v1.TestEnums.TestEnum other) {
        if (other == com.bbrownsound.flink.formats.proto.test.v1.TestEnums.TestEnum.getDefaultInstance()) return this;
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        if (!other.status_.isEmpty()) {
          if (status_.isEmpty()) {
            status_ = other.status_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureStatusIsMutable();
            status_.addAll(other.status_);
          }
          onChanged();
        }
        internalGetMutableStatusMap().mergeFrom(
            other.internalGetStatusMap());
        bitField0_ |= 0x00000004;
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                type_ = input.readEnum();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                int tmpRaw = input.readEnum();
                ensureStatusIsMutable();
                status_.add(tmpRaw);
                break;
              } // case 16
              case 18: {
                int length = input.readRawVarint32();
                int oldLimit = input.pushLimit(length);
                while(input.getBytesUntilLimit() > 0) {
                  int tmpRaw = input.readEnum();
                  ensureStatusIsMutable();
                  status_.add(tmpRaw);
                }
                input.popLimit(oldLimit);
                break;
              } // case 18
              case 26: {
                com.google.protobuf.MapEntry<java.lang.String, java.lang.Integer>
                statusMap__ = input.readMessage(
                    StatusMapDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
                internalGetMutableStatusMap().getMutableMap().put(
                    statusMap__.getKey(), statusMap__.getValue());
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int type_ = 0;
      /**
       * <code>.com.bbrownsound.flink.formats.proto.test.v1.MessageType type = 1 [json_name = "type"];</code>
       * @return The enum numeric value on the wire for type.
       */
      @java.lang.Override public int getTypeValue() {
        return type_;
      }
      /**
       * <code>.com.bbrownsound.flink.formats.proto.test.v1.MessageType type = 1 [json_name = "type"];</code>
       * @param value The enum numeric value on the wire for type to set.
       * @return This builder for chaining.
       */
      public Builder setTypeValue(int value) {
        type_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.com.bbrownsound.flink.formats.proto.test.v1.MessageType type = 1 [json_name = "type"];</code>
       * @return The type.
       */
      @java.lang.Override
      public com.bbrownsound.flink.formats.proto.test.v1.TestEnums.MessageType getType() {
        com.bbrownsound.flink.formats.proto.test.v1.TestEnums.MessageType result = com.bbrownsound.flink.formats.proto.test.v1.TestEnums.MessageType.forNumber(type_);
        return result == null ? com.bbrownsound.flink.formats.proto.test.v1.TestEnums.MessageType.UNRECOGNIZED : result;
      }
      /**
       * <code>.com.bbrownsound.flink.formats.proto.test.v1.MessageType type = 1 [json_name = "type"];</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(com.bbrownsound.flink.formats.proto.test.v1.TestEnums.MessageType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.com.bbrownsound.flink.formats.proto.test.v1.MessageType type = 1 [json_name = "type"];</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<java.lang.Integer> status_ =
        java.util.Collections.emptyList();
      private void ensureStatusIsMutable() {
        if (!((bitField0_ & 0x00000002) != 0)) {
          status_ = new java.util.ArrayList<java.lang.Integer>(status_);
          bitField0_ |= 0x00000002;
        }
      }
      /**
       * <code>repeated .com.bbrownsound.flink.formats.proto.test.v1.MessageStatus status = 2 [json_name = "status"];</code>
       * @return A list containing the status.
       */
      public java.util.List<com.bbrownsound.flink.formats.proto.test.v1.TestEnums.MessageStatus> getStatusList() {
        return new com.google.protobuf.Internal.ListAdapter<
            java.lang.Integer, com.bbrownsound.flink.formats.proto.test.v1.TestEnums.MessageStatus>(status_, status_converter_);
      }
      /**
       * <code>repeated .com.bbrownsound.flink.formats.proto.test.v1.MessageStatus status = 2 [json_name = "status"];</code>
       * @return The count of status.
       */
      public int getStatusCount() {
        return status_.size();
      }
      /**
       * <code>repeated .com.bbrownsound.flink.formats.proto.test.v1.MessageStatus status = 2 [json_name = "status"];</code>
       * @param index The index of the element to return.
       * @return The status at the given index.
       */
      public com.bbrownsound.flink.formats.proto.test.v1.TestEnums.MessageStatus getStatus(int index) {
        return status_converter_.convert(status_.get(index));
      }
      /**
       * <code>repeated .com.bbrownsound.flink.formats.proto.test.v1.MessageStatus status = 2 [json_name = "status"];</code>
       * @param index The index to set the value at.
       * @param value The status to set.
       * @return This builder for chaining.
       */
      public Builder setStatus(
          int index, com.bbrownsound.flink.formats.proto.test.v1.TestEnums.MessageStatus value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureStatusIsMutable();
        status_.set(index, value.getNumber());
        onChanged();
        return this;
      }
      /**
       * <code>repeated .com.bbrownsound.flink.formats.proto.test.v1.MessageStatus status = 2 [json_name = "status"];</code>
       * @param value The status to add.
       * @return This builder for chaining.
       */
      public Builder addStatus(com.bbrownsound.flink.formats.proto.test.v1.TestEnums.MessageStatus value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureStatusIsMutable();
        status_.add(value.getNumber());
        onChanged();
        return this;
      }
      /**
       * <code>repeated .com.bbrownsound.flink.formats.proto.test.v1.MessageStatus status = 2 [json_name = "status"];</code>
       * @param values The status to add.
       * @return This builder for chaining.
       */
      public Builder addAllStatus(
          java.lang.Iterable<? extends com.bbrownsound.flink.formats.proto.test.v1.TestEnums.MessageStatus> values) {
        ensureStatusIsMutable();
        for (com.bbrownsound.flink.formats.proto.test.v1.TestEnums.MessageStatus value : values) {
          status_.add(value.getNumber());
        }
        onChanged();
        return this;
      }
      /**
       * <code>repeated .com.bbrownsound.flink.formats.proto.test.v1.MessageStatus status = 2 [json_name = "status"];</code>
       * @return This builder for chaining.
       */
      public Builder clearStatus() {
        status_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>repeated .com.bbrownsound.flink.formats.proto.test.v1.MessageStatus status = 2 [json_name = "status"];</code>
       * @return A list containing the enum numeric values on the wire for status.
       */
      public java.util.List<java.lang.Integer>
      getStatusValueList() {
        return java.util.Collections.unmodifiableList(status_);
      }
      /**
       * <code>repeated .com.bbrownsound.flink.formats.proto.test.v1.MessageStatus status = 2 [json_name = "status"];</code>
       * @param index The index of the value to return.
       * @return The enum numeric value on the wire of status at the given index.
       */
      public int getStatusValue(int index) {
        return status_.get(index);
      }
      /**
       * <code>repeated .com.bbrownsound.flink.formats.proto.test.v1.MessageStatus status = 2 [json_name = "status"];</code>
       * @param index The index to set the value at.
       * @param value The enum numeric value on the wire for status to set.
       * @return This builder for chaining.
       */
      public Builder setStatusValue(
          int index, int value) {
        ensureStatusIsMutable();
        status_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated .com.bbrownsound.flink.formats.proto.test.v1.MessageStatus status = 2 [json_name = "status"];</code>
       * @param value The enum numeric value on the wire for status to add.
       * @return This builder for chaining.
       */
      public Builder addStatusValue(int value) {
        ensureStatusIsMutable();
        status_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated .com.bbrownsound.flink.formats.proto.test.v1.MessageStatus status = 2 [json_name = "status"];</code>
       * @param values The enum numeric values on the wire for status to add.
       * @return This builder for chaining.
       */
      public Builder addAllStatusValue(
          java.lang.Iterable<java.lang.Integer> values) {
        ensureStatusIsMutable();
        for (int value : values) {
          status_.add(value);
        }
        onChanged();
        return this;
      }

      private com.google.protobuf.MapField<
          java.lang.String, java.lang.Integer> statusMap_;
      private com.google.protobuf.MapField<java.lang.String, java.lang.Integer>
          internalGetStatusMap() {
        if (statusMap_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              StatusMapDefaultEntryHolder.defaultEntry);
        }
        return statusMap_;
      }
      private com.google.protobuf.MapField<java.lang.String, java.lang.Integer>
          internalGetMutableStatusMap() {
        if (statusMap_ == null) {
          statusMap_ = com.google.protobuf.MapField.newMapField(
              StatusMapDefaultEntryHolder.defaultEntry);
        }
        if (!statusMap_.isMutable()) {
          statusMap_ = statusMap_.copy();
        }
        bitField0_ |= 0x00000004;
        onChanged();
        return statusMap_;
      }
      public int getStatusMapCount() {
        return internalGetStatusMap().getMap().size();
      }
      /**
       * <code>map&lt;string, .com.bbrownsound.flink.formats.proto.test.v1.MessageStatus&gt; statusMap = 3 [json_name = "statusMap"];</code>
       */
      @java.lang.Override
      public boolean containsStatusMap(
          java.lang.String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        return internalGetStatusMap().getMap().containsKey(key);
      }
      /**
       * Use {@link #getStatusMapMap()} instead.
       */
      @java.lang.Override
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, com.bbrownsound.flink.formats.proto.test.v1.TestEnums.MessageStatus>
      getStatusMap() {
        return getStatusMapMap();
      }
      /**
       * <code>map&lt;string, .com.bbrownsound.flink.formats.proto.test.v1.MessageStatus&gt; statusMap = 3 [json_name = "statusMap"];</code>
       */
      @java.lang.Override
      public java.util.Map<java.lang.String, com.bbrownsound.flink.formats.proto.test.v1.TestEnums.MessageStatus>
      getStatusMapMap() {
        return internalGetAdaptedStatusMapMap(
            internalGetStatusMap().getMap());}
      /**
       * <code>map&lt;string, .com.bbrownsound.flink.formats.proto.test.v1.MessageStatus&gt; statusMap = 3 [json_name = "statusMap"];</code>
       */
      @java.lang.Override
      public /* nullable */
com.bbrownsound.flink.formats.proto.test.v1.TestEnums.MessageStatus getStatusMapOrDefault(
          java.lang.String key,
          /* nullable */
com.bbrownsound.flink.formats.proto.test.v1.TestEnums.MessageStatus defaultValue) {
        if (key == null) { throw new NullPointerException("map key"); }
        java.util.Map<java.lang.String, java.lang.Integer> map =
            internalGetStatusMap().getMap();
        return map.containsKey(key)
               ? statusMapValueConverter.doForward(map.get(key))
               : defaultValue;
      }
      /**
       * <code>map&lt;string, .com.bbrownsound.flink.formats.proto.test.v1.MessageStatus&gt; statusMap = 3 [json_name = "statusMap"];</code>
       */
      @java.lang.Override
      public com.bbrownsound.flink.formats.proto.test.v1.TestEnums.MessageStatus getStatusMapOrThrow(
          java.lang.String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        java.util.Map<java.lang.String, java.lang.Integer> map =
            internalGetStatusMap().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return statusMapValueConverter.doForward(map.get(key));
      }
      /**
       * Use {@link #getStatusMapValueMap()} instead.
       */
      @java.lang.Override
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.Integer>
      getStatusMapValue() {
        return getStatusMapValueMap();
      }
      /**
       * <code>map&lt;string, .com.bbrownsound.flink.formats.proto.test.v1.MessageStatus&gt; statusMap = 3 [json_name = "statusMap"];</code>
       */
      @java.lang.Override
      public java.util.Map<java.lang.String, java.lang.Integer>
      getStatusMapValueMap() {
        return internalGetStatusMap().getMap();
      }
      /**
       * <code>map&lt;string, .com.bbrownsound.flink.formats.proto.test.v1.MessageStatus&gt; statusMap = 3 [json_name = "statusMap"];</code>
       */
      @java.lang.Override
      public int getStatusMapValueOrDefault(
          java.lang.String key,
          int defaultValue) {
        if (key == null) { throw new NullPointerException("map key"); }
        java.util.Map<java.lang.String, java.lang.Integer> map =
            internalGetStatusMap().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, .com.bbrownsound.flink.formats.proto.test.v1.MessageStatus&gt; statusMap = 3 [json_name = "statusMap"];</code>
       */
      @java.lang.Override
      public int getStatusMapValueOrThrow(
          java.lang.String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        java.util.Map<java.lang.String, java.lang.Integer> map =
            internalGetStatusMap().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }
      public Builder clearStatusMap() {
        bitField0_ = (bitField0_ & ~0x00000004);
        internalGetMutableStatusMap().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;string, .com.bbrownsound.flink.formats.proto.test.v1.MessageStatus&gt; statusMap = 3 [json_name = "statusMap"];</code>
       */
      public Builder removeStatusMap(
          java.lang.String key) {
        if (key == null) { throw new NullPointerException("map key"); }
        internalGetMutableStatusMap().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, com.bbrownsound.flink.formats.proto.test.v1.TestEnums.MessageStatus>
          getMutableStatusMap() {
        bitField0_ |= 0x00000004;
        return internalGetAdaptedStatusMapMap(
             internalGetMutableStatusMap().getMutableMap());
      }
      /**
       * <code>map&lt;string, .com.bbrownsound.flink.formats.proto.test.v1.MessageStatus&gt; statusMap = 3 [json_name = "statusMap"];</code>
       */
      public Builder putStatusMap(
          java.lang.String key,
          com.bbrownsound.flink.formats.proto.test.v1.TestEnums.MessageStatus value) {
        if (key == null) { throw new NullPointerException("map key"); }

        internalGetMutableStatusMap().getMutableMap()
            .put(key, statusMapValueConverter.doBackward(value));
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>map&lt;string, .com.bbrownsound.flink.formats.proto.test.v1.MessageStatus&gt; statusMap = 3 [json_name = "statusMap"];</code>
       */
      public Builder putAllStatusMap(
          java.util.Map<java.lang.String, com.bbrownsound.flink.formats.proto.test.v1.TestEnums.MessageStatus> values) {
        internalGetAdaptedStatusMapMap(
            internalGetMutableStatusMap().getMutableMap())
                .putAll(values);
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.Integer>
      getMutableStatusMapValue() {
        bitField0_ |= 0x00000004;
        return internalGetMutableStatusMap().getMutableMap();
      }
      /**
       * <code>map&lt;string, .com.bbrownsound.flink.formats.proto.test.v1.MessageStatus&gt; statusMap = 3 [json_name = "statusMap"];</code>
       */
      public Builder putStatusMapValue(
          java.lang.String key,
          int value) {
        if (key == null) { throw new NullPointerException("map key"); }

        internalGetMutableStatusMap().getMutableMap()
            .put(key, value);
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>map&lt;string, .com.bbrownsound.flink.formats.proto.test.v1.MessageStatus&gt; statusMap = 3 [json_name = "statusMap"];</code>
       */
      public Builder putAllStatusMapValue(
          java.util.Map<java.lang.String, java.lang.Integer> values) {
        internalGetMutableStatusMap().getMutableMap()
            .putAll(values);
        bitField0_ |= 0x00000004;
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.bbrownsound.flink.formats.proto.test.v1.TestEnum)
    }

    // @@protoc_insertion_point(class_scope:com.bbrownsound.flink.formats.proto.test.v1.TestEnum)
    private static final com.bbrownsound.flink.formats.proto.test.v1.TestEnums.TestEnum DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.bbrownsound.flink.formats.proto.test.v1.TestEnums.TestEnum();
    }

    public static com.bbrownsound.flink.formats.proto.test.v1.TestEnums.TestEnum getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TestEnum>
        PARSER = new com.google.protobuf.AbstractParser<TestEnum>() {
      @java.lang.Override
      public TestEnum parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<TestEnum> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TestEnum> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.bbrownsound.flink.formats.proto.test.v1.TestEnums.TestEnum getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_bbrownsound_flink_formats_proto_test_v1_TestEnum_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_bbrownsound_flink_formats_proto_test_v1_TestEnum_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_bbrownsound_flink_formats_proto_test_v1_TestEnum_StatusMapEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_bbrownsound_flink_formats_proto_test_v1_TestEnum_StatusMapEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n<com/bbrownsound/flink/formats/proto/te" +
      "st/v1/test_enums.proto\022+com.bbrownsound." +
      "flink.formats.proto.test.v1\"\212\003\n\010TestEnum" +
      "\022L\n\004type\030\001 \001(\01628.com.bbrownsound.flink.f" +
      "ormats.proto.test.v1.MessageTypeR\004type\022R" +
      "\n\006status\030\002 \003(\0162:.com.bbrownsound.flink.f" +
      "ormats.proto.test.v1.MessageStatusR\006stat" +
      "us\022b\n\tstatusMap\030\003 \003(\0132D.com.bbrownsound." +
      "flink.formats.proto.test.v1.TestEnum.Sta" +
      "tusMapEntryR\tstatusMap\032x\n\016StatusMapEntry" +
      "\022\020\n\003key\030\001 \001(\tR\003key\022P\n\005value\030\002 \001(\0162:.com." +
      "bbrownsound.flink.formats.proto.test.v1." +
      "MessageStatusR\005value:\0028\001*-\n\013MessageType\022" +
      "\010\n\004TEXT\020\000\022\t\n\005IMAGE\020\001\022\t\n\005VIDEO\020\002*1\n\rMessa" +
      "geStatus\022\010\n\004SENT\020\000\022\014\n\010RECEIVED\020\001\022\010\n\004READ" +
      "\020\002B-\n+com.bbrownsound.flink.formats.prot" +
      "o.test.v1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_bbrownsound_flink_formats_proto_test_v1_TestEnum_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_bbrownsound_flink_formats_proto_test_v1_TestEnum_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_bbrownsound_flink_formats_proto_test_v1_TestEnum_descriptor,
        new java.lang.String[] { "Type", "Status", "StatusMap", });
    internal_static_com_bbrownsound_flink_formats_proto_test_v1_TestEnum_StatusMapEntry_descriptor =
      internal_static_com_bbrownsound_flink_formats_proto_test_v1_TestEnum_descriptor.getNestedTypes().get(0);
    internal_static_com_bbrownsound_flink_formats_proto_test_v1_TestEnum_StatusMapEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_bbrownsound_flink_formats_proto_test_v1_TestEnum_StatusMapEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
