// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/bbrownsound/flink/formats/proto/test/v1/test_repeated_nested.proto

package com.bbrownsound.flink.formats.proto.test.v1;

public final class TestRepeatedNested {
  private TestRepeatedNested() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RepeatedMessageTestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.bbrownsound.flink.formats.proto.test.v1.RepeatedMessageTest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.com.bbrownsound.flink.formats.proto.test.v1.RepeatedMessageTest.InnerMessageTest d = 4 [json_name = "d"];</code>
     * @return Whether the d field is set.
     */
    boolean hasD();
    /**
     * <code>.com.bbrownsound.flink.formats.proto.test.v1.RepeatedMessageTest.InnerMessageTest d = 4 [json_name = "d"];</code>
     * @return The d.
     */
    com.bbrownsound.flink.formats.proto.test.v1.TestRepeatedNested.RepeatedMessageTest.InnerMessageTest getD();
    /**
     * <code>.com.bbrownsound.flink.formats.proto.test.v1.RepeatedMessageTest.InnerMessageTest d = 4 [json_name = "d"];</code>
     */
    com.bbrownsound.flink.formats.proto.test.v1.TestRepeatedNested.RepeatedMessageTest.InnerMessageTestOrBuilder getDOrBuilder();
  }
  /**
   * Protobuf type {@code com.bbrownsound.flink.formats.proto.test.v1.RepeatedMessageTest}
   */
  public static final class RepeatedMessageTest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.bbrownsound.flink.formats.proto.test.v1.RepeatedMessageTest)
      RepeatedMessageTestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use RepeatedMessageTest.newBuilder() to construct.
    private RepeatedMessageTest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RepeatedMessageTest() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new RepeatedMessageTest();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.bbrownsound.flink.formats.proto.test.v1.TestRepeatedNested.internal_static_com_bbrownsound_flink_formats_proto_test_v1_RepeatedMessageTest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.bbrownsound.flink.formats.proto.test.v1.TestRepeatedNested.internal_static_com_bbrownsound_flink_formats_proto_test_v1_RepeatedMessageTest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.bbrownsound.flink.formats.proto.test.v1.TestRepeatedNested.RepeatedMessageTest.class, com.bbrownsound.flink.formats.proto.test.v1.TestRepeatedNested.RepeatedMessageTest.Builder.class);
    }

    public interface InnerMessageTestOrBuilder extends
        // @@protoc_insertion_point(interface_extends:com.bbrownsound.flink.formats.proto.test.v1.RepeatedMessageTest.InnerMessageTest)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>optional int32 a = 1 [json_name = "a"];</code>
       * @return Whether the a field is set.
       */
      boolean hasA();
      /**
       * <code>optional int32 a = 1 [json_name = "a"];</code>
       * @return The a.
       */
      int getA();

      /**
       * <code>optional int64 b = 2 [json_name = "b"];</code>
       * @return Whether the b field is set.
       */
      boolean hasB();
      /**
       * <code>optional int64 b = 2 [json_name = "b"];</code>
       * @return The b.
       */
      long getB();
    }
    /**
     * Protobuf type {@code com.bbrownsound.flink.formats.proto.test.v1.RepeatedMessageTest.InnerMessageTest}
     */
    public static final class InnerMessageTest extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:com.bbrownsound.flink.formats.proto.test.v1.RepeatedMessageTest.InnerMessageTest)
        InnerMessageTestOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use InnerMessageTest.newBuilder() to construct.
      private InnerMessageTest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private InnerMessageTest() {
      }

      @java.lang.Override
      @SuppressWarnings({"unused"})
      protected java.lang.Object newInstance(
          UnusedPrivateParameter unused) {
        return new InnerMessageTest();
      }

      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.bbrownsound.flink.formats.proto.test.v1.TestRepeatedNested.internal_static_com_bbrownsound_flink_formats_proto_test_v1_RepeatedMessageTest_InnerMessageTest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.bbrownsound.flink.formats.proto.test.v1.TestRepeatedNested.internal_static_com_bbrownsound_flink_formats_proto_test_v1_RepeatedMessageTest_InnerMessageTest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.bbrownsound.flink.formats.proto.test.v1.TestRepeatedNested.RepeatedMessageTest.InnerMessageTest.class, com.bbrownsound.flink.formats.proto.test.v1.TestRepeatedNested.RepeatedMessageTest.InnerMessageTest.Builder.class);
      }

      private int bitField0_;
      public static final int A_FIELD_NUMBER = 1;
      private int a_ = 0;
      /**
       * <code>optional int32 a = 1 [json_name = "a"];</code>
       * @return Whether the a field is set.
       */
      @java.lang.Override
      public boolean hasA() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional int32 a = 1 [json_name = "a"];</code>
       * @return The a.
       */
      @java.lang.Override
      public int getA() {
        return a_;
      }

      public static final int B_FIELD_NUMBER = 2;
      private long b_ = 0L;
      /**
       * <code>optional int64 b = 2 [json_name = "b"];</code>
       * @return Whether the b field is set.
       */
      @java.lang.Override
      public boolean hasB() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional int64 b = 2 [json_name = "b"];</code>
       * @return The b.
       */
      @java.lang.Override
      public long getB() {
        return b_;
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (((bitField0_ & 0x00000001) != 0)) {
          output.writeInt32(1, a_);
        }
        if (((bitField0_ & 0x00000002) != 0)) {
          output.writeInt64(2, b_);
        }
        getUnknownFields().writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) != 0)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(1, a_);
        }
        if (((bitField0_ & 0x00000002) != 0)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt64Size(2, b_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof com.bbrownsound.flink.formats.proto.test.v1.TestRepeatedNested.RepeatedMessageTest.InnerMessageTest)) {
          return super.equals(obj);
        }
        com.bbrownsound.flink.formats.proto.test.v1.TestRepeatedNested.RepeatedMessageTest.InnerMessageTest other = (com.bbrownsound.flink.formats.proto.test.v1.TestRepeatedNested.RepeatedMessageTest.InnerMessageTest) obj;

        if (hasA() != other.hasA()) return false;
        if (hasA()) {
          if (getA()
              != other.getA()) return false;
        }
        if (hasB() != other.hasB()) return false;
        if (hasB()) {
          if (getB()
              != other.getB()) return false;
        }
        if (!getUnknownFields().equals(other.getUnknownFields())) return false;
        return true;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        if (hasA()) {
          hash = (37 * hash) + A_FIELD_NUMBER;
          hash = (53 * hash) + getA();
        }
        if (hasB()) {
          hash = (37 * hash) + B_FIELD_NUMBER;
          hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
              getB());
        }
        hash = (29 * hash) + getUnknownFields().hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static com.bbrownsound.flink.formats.proto.test.v1.TestRepeatedNested.RepeatedMessageTest.InnerMessageTest parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.bbrownsound.flink.formats.proto.test.v1.TestRepeatedNested.RepeatedMessageTest.InnerMessageTest parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.bbrownsound.flink.formats.proto.test.v1.TestRepeatedNested.RepeatedMessageTest.InnerMessageTest parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.bbrownsound.flink.formats.proto.test.v1.TestRepeatedNested.RepeatedMessageTest.InnerMessageTest parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.bbrownsound.flink.formats.proto.test.v1.TestRepeatedNested.RepeatedMessageTest.InnerMessageTest parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.bbrownsound.flink.formats.proto.test.v1.TestRepeatedNested.RepeatedMessageTest.InnerMessageTest parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.bbrownsound.flink.formats.proto.test.v1.TestRepeatedNested.RepeatedMessageTest.InnerMessageTest parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.bbrownsound.flink.formats.proto.test.v1.TestRepeatedNested.RepeatedMessageTest.InnerMessageTest parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      public static com.bbrownsound.flink.formats.proto.test.v1.TestRepeatedNested.RepeatedMessageTest.InnerMessageTest parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }

      public static com.bbrownsound.flink.formats.proto.test.v1.TestRepeatedNested.RepeatedMessageTest.InnerMessageTest parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.bbrownsound.flink.formats.proto.test.v1.TestRepeatedNested.RepeatedMessageTest.InnerMessageTest parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.bbrownsound.flink.formats.proto.test.v1.TestRepeatedNested.RepeatedMessageTest.InnerMessageTest parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(com.bbrownsound.flink.formats.proto.test.v1.TestRepeatedNested.RepeatedMessageTest.InnerMessageTest prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code com.bbrownsound.flink.formats.proto.test.v1.RepeatedMessageTest.InnerMessageTest}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:com.bbrownsound.flink.formats.proto.test.v1.RepeatedMessageTest.InnerMessageTest)
          com.bbrownsound.flink.formats.proto.test.v1.TestRepeatedNested.RepeatedMessageTest.InnerMessageTestOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.bbrownsound.flink.formats.proto.test.v1.TestRepeatedNested.internal_static_com_bbrownsound_flink_formats_proto_test_v1_RepeatedMessageTest_InnerMessageTest_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.bbrownsound.flink.formats.proto.test.v1.TestRepeatedNested.internal_static_com_bbrownsound_flink_formats_proto_test_v1_RepeatedMessageTest_InnerMessageTest_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.bbrownsound.flink.formats.proto.test.v1.TestRepeatedNested.RepeatedMessageTest.InnerMessageTest.class, com.bbrownsound.flink.formats.proto.test.v1.TestRepeatedNested.RepeatedMessageTest.InnerMessageTest.Builder.class);
        }

        // Construct using com.bbrownsound.flink.formats.proto.test.v1.TestRepeatedNested.RepeatedMessageTest.InnerMessageTest.newBuilder()
        private Builder() {

        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);

        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          bitField0_ = 0;
          a_ = 0;
          b_ = 0L;
          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.bbrownsound.flink.formats.proto.test.v1.TestRepeatedNested.internal_static_com_bbrownsound_flink_formats_proto_test_v1_RepeatedMessageTest_InnerMessageTest_descriptor;
        }

        @java.lang.Override
        public com.bbrownsound.flink.formats.proto.test.v1.TestRepeatedNested.RepeatedMessageTest.InnerMessageTest getDefaultInstanceForType() {
          return com.bbrownsound.flink.formats.proto.test.v1.TestRepeatedNested.RepeatedMessageTest.InnerMessageTest.getDefaultInstance();
        }

        @java.lang.Override
        public com.bbrownsound.flink.formats.proto.test.v1.TestRepeatedNested.RepeatedMessageTest.InnerMessageTest build() {
          com.bbrownsound.flink.formats.proto.test.v1.TestRepeatedNested.RepeatedMessageTest.InnerMessageTest result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public com.bbrownsound.flink.formats.proto.test.v1.TestRepeatedNested.RepeatedMessageTest.InnerMessageTest buildPartial() {
          com.bbrownsound.flink.formats.proto.test.v1.TestRepeatedNested.RepeatedMessageTest.InnerMessageTest result = new com.bbrownsound.flink.formats.proto.test.v1.TestRepeatedNested.RepeatedMessageTest.InnerMessageTest(this);
          if (bitField0_ != 0) { buildPartial0(result); }
          onBuilt();
          return result;
        }

        private void buildPartial0(com.bbrownsound.flink.formats.proto.test.v1.TestRepeatedNested.RepeatedMessageTest.InnerMessageTest result) {
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) != 0)) {
            result.a_ = a_;
            to_bitField0_ |= 0x00000001;
          }
          if (((from_bitField0_ & 0x00000002) != 0)) {
            result.b_ = b_;
            to_bitField0_ |= 0x00000002;
          }
          result.bitField0_ |= to_bitField0_;
        }

        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.bbrownsound.flink.formats.proto.test.v1.TestRepeatedNested.RepeatedMessageTest.InnerMessageTest) {
            return mergeFrom((com.bbrownsound.flink.formats.proto.test.v1.TestRepeatedNested.RepeatedMessageTest.InnerMessageTest)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.bbrownsound.flink.formats.proto.test.v1.TestRepeatedNested.RepeatedMessageTest.InnerMessageTest other) {
          if (other == com.bbrownsound.flink.formats.proto.test.v1.TestRepeatedNested.RepeatedMessageTest.InnerMessageTest.getDefaultInstance()) return this;
          if (other.hasA()) {
            setA(other.getA());
          }
          if (other.hasB()) {
            setB(other.getB());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          if (extensionRegistry == null) {
            throw new java.lang.NullPointerException();
          }
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                case 8: {
                  a_ = input.readInt32();
                  bitField0_ |= 0x00000001;
                  break;
                } // case 8
                case 16: {
                  b_ = input.readInt64();
                  bitField0_ |= 0x00000002;
                  break;
                } // case 16
                default: {
                  if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                    done = true; // was an endgroup tag
                  }
                  break;
                } // default:
              } // switch (tag)
            } // while (!done)
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.unwrapIOException();
          } finally {
            onChanged();
          } // finally
          return this;
        }
        private int bitField0_;

        private int a_ ;
        /**
         * <code>optional int32 a = 1 [json_name = "a"];</code>
         * @return Whether the a field is set.
         */
        @java.lang.Override
        public boolean hasA() {
          return ((bitField0_ & 0x00000001) != 0);
        }
        /**
         * <code>optional int32 a = 1 [json_name = "a"];</code>
         * @return The a.
         */
        @java.lang.Override
        public int getA() {
          return a_;
        }
        /**
         * <code>optional int32 a = 1 [json_name = "a"];</code>
         * @param value The a to set.
         * @return This builder for chaining.
         */
        public Builder setA(int value) {

          a_ = value;
          bitField0_ |= 0x00000001;
          onChanged();
          return this;
        }
        /**
         * <code>optional int32 a = 1 [json_name = "a"];</code>
         * @return This builder for chaining.
         */
        public Builder clearA() {
          bitField0_ = (bitField0_ & ~0x00000001);
          a_ = 0;
          onChanged();
          return this;
        }

        private long b_ ;
        /**
         * <code>optional int64 b = 2 [json_name = "b"];</code>
         * @return Whether the b field is set.
         */
        @java.lang.Override
        public boolean hasB() {
          return ((bitField0_ & 0x00000002) != 0);
        }
        /**
         * <code>optional int64 b = 2 [json_name = "b"];</code>
         * @return The b.
         */
        @java.lang.Override
        public long getB() {
          return b_;
        }
        /**
         * <code>optional int64 b = 2 [json_name = "b"];</code>
         * @param value The b to set.
         * @return This builder for chaining.
         */
        public Builder setB(long value) {

          b_ = value;
          bitField0_ |= 0x00000002;
          onChanged();
          return this;
        }
        /**
         * <code>optional int64 b = 2 [json_name = "b"];</code>
         * @return This builder for chaining.
         */
        public Builder clearB() {
          bitField0_ = (bitField0_ & ~0x00000002);
          b_ = 0L;
          onChanged();
          return this;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:com.bbrownsound.flink.formats.proto.test.v1.RepeatedMessageTest.InnerMessageTest)
      }

      // @@protoc_insertion_point(class_scope:com.bbrownsound.flink.formats.proto.test.v1.RepeatedMessageTest.InnerMessageTest)
      private static final com.bbrownsound.flink.formats.proto.test.v1.TestRepeatedNested.RepeatedMessageTest.InnerMessageTest DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new com.bbrownsound.flink.formats.proto.test.v1.TestRepeatedNested.RepeatedMessageTest.InnerMessageTest();
      }

      public static com.bbrownsound.flink.formats.proto.test.v1.TestRepeatedNested.RepeatedMessageTest.InnerMessageTest getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<InnerMessageTest>
          PARSER = new com.google.protobuf.AbstractParser<InnerMessageTest>() {
        @java.lang.Override
        public InnerMessageTest parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          Builder builder = newBuilder();
          try {
            builder.mergeFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(builder.buildPartial());
          } catch (com.google.protobuf.UninitializedMessageException e) {
            throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
          } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(e)
                .setUnfinishedMessage(builder.buildPartial());
          }
          return builder.buildPartial();
        }
      };

      public static com.google.protobuf.Parser<InnerMessageTest> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<InnerMessageTest> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public com.bbrownsound.flink.formats.proto.test.v1.TestRepeatedNested.RepeatedMessageTest.InnerMessageTest getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public static final int D_FIELD_NUMBER = 4;
    private com.bbrownsound.flink.formats.proto.test.v1.TestRepeatedNested.RepeatedMessageTest.InnerMessageTest d_;
    /**
     * <code>.com.bbrownsound.flink.formats.proto.test.v1.RepeatedMessageTest.InnerMessageTest d = 4 [json_name = "d"];</code>
     * @return Whether the d field is set.
     */
    @java.lang.Override
    public boolean hasD() {
      return d_ != null;
    }
    /**
     * <code>.com.bbrownsound.flink.formats.proto.test.v1.RepeatedMessageTest.InnerMessageTest d = 4 [json_name = "d"];</code>
     * @return The d.
     */
    @java.lang.Override
    public com.bbrownsound.flink.formats.proto.test.v1.TestRepeatedNested.RepeatedMessageTest.InnerMessageTest getD() {
      return d_ == null ? com.bbrownsound.flink.formats.proto.test.v1.TestRepeatedNested.RepeatedMessageTest.InnerMessageTest.getDefaultInstance() : d_;
    }
    /**
     * <code>.com.bbrownsound.flink.formats.proto.test.v1.RepeatedMessageTest.InnerMessageTest d = 4 [json_name = "d"];</code>
     */
    @java.lang.Override
    public com.bbrownsound.flink.formats.proto.test.v1.TestRepeatedNested.RepeatedMessageTest.InnerMessageTestOrBuilder getDOrBuilder() {
      return d_ == null ? com.bbrownsound.flink.formats.proto.test.v1.TestRepeatedNested.RepeatedMessageTest.InnerMessageTest.getDefaultInstance() : d_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (d_ != null) {
        output.writeMessage(4, getD());
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (d_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getD());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.bbrownsound.flink.formats.proto.test.v1.TestRepeatedNested.RepeatedMessageTest)) {
        return super.equals(obj);
      }
      com.bbrownsound.flink.formats.proto.test.v1.TestRepeatedNested.RepeatedMessageTest other = (com.bbrownsound.flink.formats.proto.test.v1.TestRepeatedNested.RepeatedMessageTest) obj;

      if (hasD() != other.hasD()) return false;
      if (hasD()) {
        if (!getD()
            .equals(other.getD())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasD()) {
        hash = (37 * hash) + D_FIELD_NUMBER;
        hash = (53 * hash) + getD().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.bbrownsound.flink.formats.proto.test.v1.TestRepeatedNested.RepeatedMessageTest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bbrownsound.flink.formats.proto.test.v1.TestRepeatedNested.RepeatedMessageTest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bbrownsound.flink.formats.proto.test.v1.TestRepeatedNested.RepeatedMessageTest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bbrownsound.flink.formats.proto.test.v1.TestRepeatedNested.RepeatedMessageTest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bbrownsound.flink.formats.proto.test.v1.TestRepeatedNested.RepeatedMessageTest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.bbrownsound.flink.formats.proto.test.v1.TestRepeatedNested.RepeatedMessageTest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.bbrownsound.flink.formats.proto.test.v1.TestRepeatedNested.RepeatedMessageTest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.bbrownsound.flink.formats.proto.test.v1.TestRepeatedNested.RepeatedMessageTest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.bbrownsound.flink.formats.proto.test.v1.TestRepeatedNested.RepeatedMessageTest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.bbrownsound.flink.formats.proto.test.v1.TestRepeatedNested.RepeatedMessageTest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.bbrownsound.flink.formats.proto.test.v1.TestRepeatedNested.RepeatedMessageTest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.bbrownsound.flink.formats.proto.test.v1.TestRepeatedNested.RepeatedMessageTest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.bbrownsound.flink.formats.proto.test.v1.TestRepeatedNested.RepeatedMessageTest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.bbrownsound.flink.formats.proto.test.v1.RepeatedMessageTest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.bbrownsound.flink.formats.proto.test.v1.RepeatedMessageTest)
        com.bbrownsound.flink.formats.proto.test.v1.TestRepeatedNested.RepeatedMessageTestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.bbrownsound.flink.formats.proto.test.v1.TestRepeatedNested.internal_static_com_bbrownsound_flink_formats_proto_test_v1_RepeatedMessageTest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.bbrownsound.flink.formats.proto.test.v1.TestRepeatedNested.internal_static_com_bbrownsound_flink_formats_proto_test_v1_RepeatedMessageTest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.bbrownsound.flink.formats.proto.test.v1.TestRepeatedNested.RepeatedMessageTest.class, com.bbrownsound.flink.formats.proto.test.v1.TestRepeatedNested.RepeatedMessageTest.Builder.class);
      }

      // Construct using com.bbrownsound.flink.formats.proto.test.v1.TestRepeatedNested.RepeatedMessageTest.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        d_ = null;
        if (dBuilder_ != null) {
          dBuilder_.dispose();
          dBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.bbrownsound.flink.formats.proto.test.v1.TestRepeatedNested.internal_static_com_bbrownsound_flink_formats_proto_test_v1_RepeatedMessageTest_descriptor;
      }

      @java.lang.Override
      public com.bbrownsound.flink.formats.proto.test.v1.TestRepeatedNested.RepeatedMessageTest getDefaultInstanceForType() {
        return com.bbrownsound.flink.formats.proto.test.v1.TestRepeatedNested.RepeatedMessageTest.getDefaultInstance();
      }

      @java.lang.Override
      public com.bbrownsound.flink.formats.proto.test.v1.TestRepeatedNested.RepeatedMessageTest build() {
        com.bbrownsound.flink.formats.proto.test.v1.TestRepeatedNested.RepeatedMessageTest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.bbrownsound.flink.formats.proto.test.v1.TestRepeatedNested.RepeatedMessageTest buildPartial() {
        com.bbrownsound.flink.formats.proto.test.v1.TestRepeatedNested.RepeatedMessageTest result = new com.bbrownsound.flink.formats.proto.test.v1.TestRepeatedNested.RepeatedMessageTest(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.bbrownsound.flink.formats.proto.test.v1.TestRepeatedNested.RepeatedMessageTest result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.d_ = dBuilder_ == null
              ? d_
              : dBuilder_.build();
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.bbrownsound.flink.formats.proto.test.v1.TestRepeatedNested.RepeatedMessageTest) {
          return mergeFrom((com.bbrownsound.flink.formats.proto.test.v1.TestRepeatedNested.RepeatedMessageTest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.bbrownsound.flink.formats.proto.test.v1.TestRepeatedNested.RepeatedMessageTest other) {
        if (other == com.bbrownsound.flink.formats.proto.test.v1.TestRepeatedNested.RepeatedMessageTest.getDefaultInstance()) return this;
        if (other.hasD()) {
          mergeD(other.getD());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 34: {
                input.readMessage(
                    getDFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000001;
                break;
              } // case 34
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private com.bbrownsound.flink.formats.proto.test.v1.TestRepeatedNested.RepeatedMessageTest.InnerMessageTest d_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.bbrownsound.flink.formats.proto.test.v1.TestRepeatedNested.RepeatedMessageTest.InnerMessageTest, com.bbrownsound.flink.formats.proto.test.v1.TestRepeatedNested.RepeatedMessageTest.InnerMessageTest.Builder, com.bbrownsound.flink.formats.proto.test.v1.TestRepeatedNested.RepeatedMessageTest.InnerMessageTestOrBuilder> dBuilder_;
      /**
       * <code>.com.bbrownsound.flink.formats.proto.test.v1.RepeatedMessageTest.InnerMessageTest d = 4 [json_name = "d"];</code>
       * @return Whether the d field is set.
       */
      public boolean hasD() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>.com.bbrownsound.flink.formats.proto.test.v1.RepeatedMessageTest.InnerMessageTest d = 4 [json_name = "d"];</code>
       * @return The d.
       */
      public com.bbrownsound.flink.formats.proto.test.v1.TestRepeatedNested.RepeatedMessageTest.InnerMessageTest getD() {
        if (dBuilder_ == null) {
          return d_ == null ? com.bbrownsound.flink.formats.proto.test.v1.TestRepeatedNested.RepeatedMessageTest.InnerMessageTest.getDefaultInstance() : d_;
        } else {
          return dBuilder_.getMessage();
        }
      }
      /**
       * <code>.com.bbrownsound.flink.formats.proto.test.v1.RepeatedMessageTest.InnerMessageTest d = 4 [json_name = "d"];</code>
       */
      public Builder setD(com.bbrownsound.flink.formats.proto.test.v1.TestRepeatedNested.RepeatedMessageTest.InnerMessageTest value) {
        if (dBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          d_ = value;
        } else {
          dBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.com.bbrownsound.flink.formats.proto.test.v1.RepeatedMessageTest.InnerMessageTest d = 4 [json_name = "d"];</code>
       */
      public Builder setD(
          com.bbrownsound.flink.formats.proto.test.v1.TestRepeatedNested.RepeatedMessageTest.InnerMessageTest.Builder builderForValue) {
        if (dBuilder_ == null) {
          d_ = builderForValue.build();
        } else {
          dBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.com.bbrownsound.flink.formats.proto.test.v1.RepeatedMessageTest.InnerMessageTest d = 4 [json_name = "d"];</code>
       */
      public Builder mergeD(com.bbrownsound.flink.formats.proto.test.v1.TestRepeatedNested.RepeatedMessageTest.InnerMessageTest value) {
        if (dBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0) &&
            d_ != null &&
            d_ != com.bbrownsound.flink.formats.proto.test.v1.TestRepeatedNested.RepeatedMessageTest.InnerMessageTest.getDefaultInstance()) {
            getDBuilder().mergeFrom(value);
          } else {
            d_ = value;
          }
        } else {
          dBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.com.bbrownsound.flink.formats.proto.test.v1.RepeatedMessageTest.InnerMessageTest d = 4 [json_name = "d"];</code>
       */
      public Builder clearD() {
        bitField0_ = (bitField0_ & ~0x00000001);
        d_ = null;
        if (dBuilder_ != null) {
          dBuilder_.dispose();
          dBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.com.bbrownsound.flink.formats.proto.test.v1.RepeatedMessageTest.InnerMessageTest d = 4 [json_name = "d"];</code>
       */
      public com.bbrownsound.flink.formats.proto.test.v1.TestRepeatedNested.RepeatedMessageTest.InnerMessageTest.Builder getDBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getDFieldBuilder().getBuilder();
      }
      /**
       * <code>.com.bbrownsound.flink.formats.proto.test.v1.RepeatedMessageTest.InnerMessageTest d = 4 [json_name = "d"];</code>
       */
      public com.bbrownsound.flink.formats.proto.test.v1.TestRepeatedNested.RepeatedMessageTest.InnerMessageTestOrBuilder getDOrBuilder() {
        if (dBuilder_ != null) {
          return dBuilder_.getMessageOrBuilder();
        } else {
          return d_ == null ?
              com.bbrownsound.flink.formats.proto.test.v1.TestRepeatedNested.RepeatedMessageTest.InnerMessageTest.getDefaultInstance() : d_;
        }
      }
      /**
       * <code>.com.bbrownsound.flink.formats.proto.test.v1.RepeatedMessageTest.InnerMessageTest d = 4 [json_name = "d"];</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.bbrownsound.flink.formats.proto.test.v1.TestRepeatedNested.RepeatedMessageTest.InnerMessageTest, com.bbrownsound.flink.formats.proto.test.v1.TestRepeatedNested.RepeatedMessageTest.InnerMessageTest.Builder, com.bbrownsound.flink.formats.proto.test.v1.TestRepeatedNested.RepeatedMessageTest.InnerMessageTestOrBuilder> 
          getDFieldBuilder() {
        if (dBuilder_ == null) {
          dBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.bbrownsound.flink.formats.proto.test.v1.TestRepeatedNested.RepeatedMessageTest.InnerMessageTest, com.bbrownsound.flink.formats.proto.test.v1.TestRepeatedNested.RepeatedMessageTest.InnerMessageTest.Builder, com.bbrownsound.flink.formats.proto.test.v1.TestRepeatedNested.RepeatedMessageTest.InnerMessageTestOrBuilder>(
                  getD(),
                  getParentForChildren(),
                  isClean());
          d_ = null;
        }
        return dBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.bbrownsound.flink.formats.proto.test.v1.RepeatedMessageTest)
    }

    // @@protoc_insertion_point(class_scope:com.bbrownsound.flink.formats.proto.test.v1.RepeatedMessageTest)
    private static final com.bbrownsound.flink.formats.proto.test.v1.TestRepeatedNested.RepeatedMessageTest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.bbrownsound.flink.formats.proto.test.v1.TestRepeatedNested.RepeatedMessageTest();
    }

    public static com.bbrownsound.flink.formats.proto.test.v1.TestRepeatedNested.RepeatedMessageTest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RepeatedMessageTest>
        PARSER = new com.google.protobuf.AbstractParser<RepeatedMessageTest>() {
      @java.lang.Override
      public RepeatedMessageTest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<RepeatedMessageTest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RepeatedMessageTest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.bbrownsound.flink.formats.proto.test.v1.TestRepeatedNested.RepeatedMessageTest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_bbrownsound_flink_formats_proto_test_v1_RepeatedMessageTest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_bbrownsound_flink_formats_proto_test_v1_RepeatedMessageTest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_bbrownsound_flink_formats_proto_test_v1_RepeatedMessageTest_InnerMessageTest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_bbrownsound_flink_formats_proto_test_v1_RepeatedMessageTest_InnerMessageTest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\nFcom/bbrownsound/flink/formats/proto/te" +
      "st/v1/test_repeated_nested.proto\022+com.bb" +
      "rownsound.flink.formats.proto.test.v1\"\274\001" +
      "\n\023RepeatedMessageTest\022_\n\001d\030\004 \001(\0132Q.com.b" +
      "brownsound.flink.formats.proto.test.v1.R" +
      "epeatedMessageTest.InnerMessageTestR\001d\032D" +
      "\n\020InnerMessageTest\022\021\n\001a\030\001 \001(\005H\000R\001a\210\001\001\022\021\n" +
      "\001b\030\002 \001(\003H\001R\001b\210\001\001B\004\n\002_aB\004\n\002_bB-\n+com.bbro" +
      "wnsound.flink.formats.proto.test.v1b\006pro" +
      "to3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_bbrownsound_flink_formats_proto_test_v1_RepeatedMessageTest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_bbrownsound_flink_formats_proto_test_v1_RepeatedMessageTest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_bbrownsound_flink_formats_proto_test_v1_RepeatedMessageTest_descriptor,
        new java.lang.String[] { "D", });
    internal_static_com_bbrownsound_flink_formats_proto_test_v1_RepeatedMessageTest_InnerMessageTest_descriptor =
      internal_static_com_bbrownsound_flink_formats_proto_test_v1_RepeatedMessageTest_descriptor.getNestedTypes().get(0);
    internal_static_com_bbrownsound_flink_formats_proto_test_v1_RepeatedMessageTest_InnerMessageTest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_bbrownsound_flink_formats_proto_test_v1_RepeatedMessageTest_InnerMessageTest_descriptor,
        new java.lang.String[] { "A", "B", "A", "B", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
